-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.1.19-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win32
-- HeidiSQL Versión:             9.4.0.5170
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para tabla latigazo.fichas
CREATE TABLE IF NOT EXISTS `fichas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `semana` int(11) DEFAULT NULL,
  `titulo` varchar(250) DEFAULT NULL,
  `numero` char(6) DEFAULT NULL,
  `tipo` varchar(250) DEFAULT NULL,
  `descripcion` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=506 DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla latigazo.fichas: ~505 rows (aproximadamente)
/*!40000 ALTER TABLE `fichas` DISABLE KEYS */;
INSERT INTO `fichas` (`id`, `semana`, `titulo`, `numero`, `tipo`, `descripcion`) VALUES
	(1, 1, 'OBSERVO A MI BEBE', '1', 'VidaFamilia', '[]'),
	(2, 2, '¿CÓMO CALMO A MI BEBE?', '2', 'VidaFamilia', '[]'),
	(3, 3, '¿COMO ES MI BEBE?', '3', 'VidaFamilia', '[]'),
	(4, 4, 'CONVERSO CON MI BEBE', '4', 'VidaFamilia', '[]'),
	(5, 5, 'ME GUSTA  QUE MAMA ME ABRACE', '5', 'VidaFamilia', '[]'),
	(6, 5, 'JUEGA CON TU BEBE DEMOSTRÁNDOLE TU AMOR Y CARIÑO', '94', 'JugandoAprendo', '["Mamá juega con su bebe demostrándole amor : cargándolo, arrullándolo, meciéndolo despacio demostrando alegría y entusiasmo"]'),
	(7, 6, 'ME GUSTA  CUANDO CANTAS', '6', 'VidaFamilia', '[]'),
	(8, 6, '¿COMO TE PERCIBE TU BEBÉ?', '95', 'JugandoAprendo', '["Mamá atiende tranquila a su bebe y lo hace sentir bien."]'),
	(9, 7, 'EL SUEÑO DE TU BEBE', '8', 'VidaFamilia', '[]'),
	(10, 7, 'MI  BEBE ME ESCUCHA SIEMPRE', '96', 'JugandoAprendo', '["El bebé se siente feliz cuando escucha a mamá."]'),
	(11, 8, 'ME GUSTA TU DELICADEZA', '7', 'VidaFamilia', '[]'),
	(12, 8, 'JUEGA CON TU BEBE DEMOSTRÁNDOLE TU AMOR Y CARIÑO', '94', 'VidaFamilia', '[]'),
	(13, 8, 'JUEGA CON TU BEBE DEMOSTRÁNDOLE TU AMOR Y CARIÑO', '94', 'JugandoAprendo', '["El bebé se siente feliz cuando escucha a mamá."]'),
	(14, 9, 'IMITAR LOS SONIDOS QUE HACE MI BEBE', '10', 'VidaFamilia', '[]'),
	(15, 9, 'JUGANDO CON MÍ BEBE.', '97', 'JugandoAprendo', '["El niño/a fija su mirada con muchos interés en los objetos que están cerca de él.","Observa con interés las actividades que realizan las personas a su alrededor","Explora el ambiente en confianza según sus posibilidades"]'),
	(16, 9, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(17, 10, 'IMITAR LOS SONIDOS QUE HACE ÉL BEBE', '10', 'VidaFamilia', '[]'),
	(18, 10, 'MIS OJITOS', '98', 'JugandoAprendo', '["Sigue con la mirada a su cuidador o lo objetos que se le muestra.","Expresa sus emociones, deseos y/o necesidades utilizando variados movimientos corporales y gestuales (agita brazos, estira piernas, mueve cabeza, frunce el ceño)"]'),
	(19, 10, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(20, 11, '¡BUUU!', '11', 'VidaFamilia', '[]'),
	(21, 11, 'MANITO  MANITO', '99', 'JugandoAprendo', '["Reconoce los gestos, la voz de su cuidador y sonidos familiares, respondiendo con la mirada, mímica o movimientos.","Mueve libremente y con energía brazos y piernas (p.e. juega activamente con manos y pies)"]'),
	(22, 11, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(23, 12, '¡BUUU!', '11', 'VidaFamilia', '[]'),
	(24, 12, 'SUENA LA SONAJA', '100', 'JugandoAprendo', '["El niño/a busca la sonaja con la mira o movimientos, sonidos o gestos frente al sonido de la misma.","Mueve libremente y con energía brazos y piernas (p.e. juega activamente con manos y pies)","Coge objetos pequeños (que entran en su mano) utilizando la presión palmar"]'),
	(25, 12, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(26, 13, 'CARAS GRACIOSAS', '12', 'VidaFamilia', '[]'),
	(27, 13, 'QUIERO TOCAR LO QUE VEO', '101', 'JugandoAprendo', '["El niño/a Intenta alcanzar objetos con su mano, aunque aún no pueda sujetarlos.","Estira sus brazos para alcanzar objetos que llamen su atención"]'),
	(28, 13, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(29, 14, 'CARAS GRACIOSAS', '12', 'VidaFamilia', '[]'),
	(30, 14, 'OBSERVO  MI ENTORNO', '102', 'JugandoAprendo', '["El niño/a gira la cabeza o cuerpo  para seguir le movimiento del juguete que la mama le presenta","Observa con interés las actividades que realizan las personas a su alrededor.","Expresa sus emociones, deseos y/o necesidades utilizando variados movimientos corporales y gestuales (agita brazos, estira piernas, mueve cabeza, frunce el ceño)"]'),
	(31, 14, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(32, 15, 'DESCUBRO MI CUERPO', '13', 'VidaFamilia', '[]'),
	(33, 15, 'AGARRAR Y SOLTAR', '103', 'JugandoAprendo', '["El niño/a  sostiene la sonaja por un momento breve.","El bebe sostiene y mueve la sonaja por unos segundos.","Manipula objetos que tiene en sus manos vivenciando espontáneamente las características de los objetos: forma, peso, textura, temperatura."]'),
	(34, 15, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(35, 16, 'DESCUBRO MI CUERPO', '13', 'VidaFamilia', '[]'),
	(36, 16, 'EXPLORAR LA SONAJA', '104', 'JugandoAprendo', '["El niño/a coge la sonaja y se lo lleva a la boca para chuparla o morderla","El niño/a sostiene y mueve la sonaja por unos segundos.","Coge objetos pequeños (que entran en su mano) utilizando la prensión palmar.","Manipula objetos que tiene en sus manos vivenciando espontáneamente las características de los objetos: forma, peso, textura, temperatura"]'),
	(37, 16, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(38, 17, 'MIS PRIMEROS DESCUBRIMIENTOS', '14', 'VidaFamilia', '[]'),
	(39, 17, 'ALCANZAR LA SONAJA QUE ESTÁ LEJOS', '105', 'JugandoAprendo', '["Intenta alcanzar objetos con su mano, cuando su mama se lo muestra.","Estira sus brazos para alcanzar objetos que llamen su atención","Coge objetos pequeños (que entran en su mano) utilizlando la prensión palmar","Coge objetos que están a su alcance con ambas manos y se lo lleva a la boca."]'),
	(40, 17, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(41, 18, 'MIS PRIMEROS DESCUBRIMIENTOS', '14', 'VidaFamilia', '[]'),
	(42, 18, 'DESCUBRO EL ARO DE JEBE', '106', 'JugandoAprendo', '["El niño/a coge el aro y se lo lleva a la boca para chuparlo o morderlo.","Estira sus brazos para alcanzar objetos que llamen su atención","Coge objetos pequeños (que entran en su mano) utilizando la prensión palmar.","Intenta alcanzar objetos con su mano, aunque aún se le escapen"]'),
	(43, 18, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(44, 19, 'METO  MIS MANOS Y MIS PIES', '15', 'VidaFamilia', '[]'),
	(45, 19, 'HAGO SONAR LA SONAJA', '107', 'JugandoAprendo', '["El niño/a  coge la sonaja y la mueve para que suene.","Estira sus brazos para alcanzar objetos que llamen su atención","Coge objetos que están a su alcance con ambas manos y se lo lleva a la boca","Manipula objetos que tiene en sus manos vivenciando espontáneamente las características de los objetos: forma, peso, textura, temperatura."]'),
	(46, 19, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(47, 20, 'METO  MIS MANOS Y MIS PIES', '15', 'VidaFamilia', '[]'),
	(48, 20, 'HAGO SONAR LA SONAJA', '107', 'JugandoAprendo', '["Produce con los objetos diversos sonidos que le son agradables","Estira sus brazos para alcanzar objetos que llamen su atención.","Coge objetos que están a su alcance con ambas manos y se lo lleva a la boca"]'),
	(49, 20, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(50, 21, 'COSQUILLITAS Y PATADITAS', '16', 'VidaFamilia', '[]'),
	(51, 21, 'DISFRUTAMOS DE LA MÚSICA  JUNTOS', '108', 'JugandoAprendo', '["El niño/a se divierte en los brazos de mama al ritmo de la música que ella le canta.","Reconoce a la persona que lo cuida.","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él)"]'),
	(52, 21, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(53, 22, 'COSQUILLITAS Y PATADITAS', '16', 'VidaFamilia', '[]'),
	(54, 22, 'MIRA COMO RUEDA', '109', 'JugandoAprendo', '["El niño/a observa la botella que su cuidador hacer rodar delante de él.","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)."]'),
	(55, 22, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(56, 23, 'SIENTO  EL AGUA Y EL JABÓN', '17', 'VidaFamilia', '[]'),
	(57, 23, '¡ENCUÉNTRAME¡', '110', 'JugandoAprendo', '["El niño/a se divierte y expresa emociones cuando la mama se tapa o destapa la cara.","Reconoce a la persona que lo cuida.","Pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura"]'),
	(58, 23, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(59, 24, 'SIENTO  EL AGUA Y EL JABÓN', '17', 'VidaFamilia', '[]'),
	(60, 24, 'AGITO LAS MARACAS', '111', 'JugandoAprendo', '["El niño/a coge y explora las marcas, las hace sonar o se las lleva a la boca.","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)"]'),
	(61, 24, 'SALUDO AL BEBE', '112', 'JugandoAprendo', '["El niño/a observa con atención el juego que el cuidador hace con los títeres","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.).","Pasa un objeto de una mano a otra.","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él)"]'),
	(62, 24, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(63, 25, 'MMMM, ¿QUÉ ES?', '18', 'VidaFamilia', '[]'),
	(64, 25, 'GOLPEO EL ARO', '113', 'JugandoAprendo', '["El niño/a observa cómo se mueve el aro e intenta o lo alcanza a golpear  con la mano.","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Pasa un objeto de una mano a otra"]'),
	(65, 25, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(66, 26, 'MMMM, ¿QUÉ ES?', '18', 'VidaFamilia', '[]'),
	(67, 26, 'TE VEO  Y NO TE VEO', '114', 'JugandoAprendo', '["El niño/a se divierte y juega con su mama a taparse la cara con el pañuelo","Reconoce a la persona que lo cuida.","Se pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
	(68, 26, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(69, 27, 'ME GUSTAN TUS CARICIAS TU VOZ', '19', 'VidaFamilia', '[]'),
	(70, 27, 'AGITAR LA SONAJA CON FUERZA', '115', 'JugandoAprendo', '["El niño/a hace sonar la sonaja moviéndola en diferentes direcciones","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
	(71, 27, 'SACO LOS CUBOS DEL RECIPIENTE', '116', 'JugandoAprendo', '["El niño/a Introduce y saca objetos pequeños de un recipiente (con todos los dedos)","Pasa un objeto de una mano a otra.","Recoge objetos pequeños arrastrando los dedos (movimientos rastrillo).","Realiza diversas acciones con y entre los objetos:  los golpea entre sí, los frota, los saca y los mete de un recipiente, etc."]'),
	(72, 27, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(73, 28, 'ME GUSTAN TUS CARICIAS TU VOZ', '19', 'VidaFamilia', '[]'),
	(74, 28, 'SACO LOS CUBOS DE RECIPIENTE', '116', 'JugandoAprendo', '["Introduce y saca objetos pequeños de un recipiente (con todos los dedos)","Pasa un objeto de una mano a otra.","Recoge objetos pequeños arrastrando los dedos (movimientos rastrillo).","Realiza diversas acciones con y entre los objetos:  los golpea entre sí, los frota, los saca y los mete de un recipiente, etc."]'),
	(75, 28, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(76, 29, 'SE QUIÉNES SON', '20', 'VidaFamilia', '[]'),
	(77, 29, 'ATRAPO EL ARO', '117', 'JugandoAprendo', '["El niño/a Se desplaza intentado coger el aro","Observa la trayectoria de los objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Observa con interés las actividades que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)"]'),
	(78, 29, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(79, 30, 'SE QUIÉNES SON', '20', 'VidaFamilia', '[]'),
	(80, 30, 'JUGANDO CON LA PELOTA DE TRAPO', '118', 'JugandoAprendo', '["El niño/a de desplaza  intentado coger la pelota","Observa la trayectoria de los objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
	(81, 30, '¿A DÓNDE SE FUE MI JUGUETE?', '119', 'JugandoAprendo', '["El niño/a se encuentra el juguete que está escondido debajo del pañuelo","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
	(82, 30, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(83, 31, 'CUÉNTAME HISTORIAS', '21', 'VidaFamilia', '[]'),
	(84, 31, 'VOLTEO EL RECIPIENTE CON LOS CUBOS', '120', 'JugandoAprendo', '["El niño/a voltea el recipiente para que caigan los cubos.","Pasa un objeto de una mano a otra.","Observa la trayectoria de los objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
	(85, 31, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(86, 32, 'NUESTRAS CANCIONES', '22', 'VidaFamilia', '[]'),
	(87, 32, 'GOLPEO LAS MARACAS COMO TAMBOR', '121', 'JugandoAprendo', '["El niño/a golpea las maracas contra un recipiente como si fuera tambor y se divierte con los sonidos que hace.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Pasa un objeto de una mano a otra.","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él).","Reacciona a través del movimiento y/o emitiendo sonidos al reconocer melodías conocidas (balancea su cuerpo, moviendo la cabeza)"]'),
	(88, 32, 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(89, 33, 'SUCIO O LIMPIO', '23', 'VidaFamilia', '[]'),
	(90, 33, 'ATRAPO LA PELOTA', '122', 'JugandoAprendo', '["El niño/a  atrapa o intenta atrapar la pelota.","Observa la trayectoria de objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad."]'),
	(91, 33, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El bebé disfruta la canción."]'),
	(92, 34, 'SUCIO O LIMPIO', '23', 'VidaFamilia', '[]'),
	(93, 34, 'RUEDO LA BOTELLA HACIA TI', '123', 'JugandoAprendo', '["El niño/a observa con atención e intenta coger la botella mientras rueda.","Pasa un objeto de una mano a otra.","Observa la trayectoria de objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Realiza diversas acciones con y entre los objetos: los golpea entre sí, los frota, los saca y los mete de un recipiente, etc.","Explora el ambiente con confianza, según sus posibilidades"]'),
	(94, 34, 'CANCIÓN', '0', 'CuentameCuento', '["El niño/a  disfruta de la canción y trata de imitar algunos sonidos."]'),
	(95, 35, 'QUIERO TOCAR  LO QUE COMO', '24', 'VidaFamilia', '[]'),
	(96, 35, 'SACO AFUERA LOS BLOQUES', '124', 'JugandoAprendo', '["El niño/a saca los cubos del recipiente.","Recoge objetos pequeños arrastrando los dedos (movimientos de rastrillo).","Pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Realiza diversas acciones con y entre los objetos: los golpea entre sí, los frota, los saca y los mete de un recipiente, etc"]'),
	(97, 35, 'EL COLLAR DE AROS', '125', 'JugandoAprendo', '["El niño/a Explora los objetos con manos y/o boca.","Observa con interés las actividades que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)","Pasa un objeto de una mano a otra."]'),
	(98, 35, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño señala imágenes que ve."]'),
	(99, 36, 'QUIERO TOCAR  LO QUE COMO', '24', 'VidaFamilia', '[]'),
	(100, 36, 'APAREZCO Y DESAPAREZCO', '126', 'JugandoAprendo', '["Observa con atención a mamá, mientras esta hace aparecer y desaparecer al juguete.","Pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición:  textura, peso, forma, temperatura."]'),
	(101, 36, 'CANCIÓN', '0', 'CuentameCuento', '["El niño señala imágenes que ve."]'),
	(102, 37, 'EXPLORO LOS OBJETOS DEL HOGAR', '25', 'VidaFamilia', '[]'),
	(103, 37, 'JALO EL ARO', '127', 'JugandoAprendo', '["El niño/a jala el aro para acercarlo a él.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se meta en cajas, acomodando su cuerpo de acuerdo a sus posibilidades."]'),
	(104, 37, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
	(105, 38, 'EXPLORO LOS OBJETOS DEL HOGAR', '25', 'VidaFamilia', '[]'),
	(106, 38, 'EXPLORO DOS TEXTURAS DIFERENTES', '129', 'JugandoAprendo', '["El niño/a se mantiene sentado sin ayuda mientras juega con las pelotas.","Pasa un objeto de una mano a otra (6-9m).","Realiza diversas acciones con y entre los objetos: los golpea entre sí, los frota, los saca y los mete de un recipiente, etc. (6-9m).","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él) (6-9m).","Imita la entonación del adulto al escuchar conversaciones (6-9m)"]'),
	(107, 38, 'GATEO POR EL TÚNEL', '128', 'JugandoAprendo', '["Se desplaza gateando por el túnel.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Explora el ambiente con confianza, según sus posibilidades.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se meta en cajas, acomodando su cuerpo de acuerdo a sus posibilidades."]'),
	(108, 38, 'CANCIÓN', '0', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
	(109, 39, 'ACCIONES DE CORTESÍA', '26', 'VidaFamilia', '[]'),
	(110, 39, 'GOLPEO LOS CUBOS', '131', 'JugandoAprendo', '["El niño/a golpe el cubo disfrutando de los sonidos que hace.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Escucha diversos sonidos e intenta imitarlos vocalizando con claridad dos sílabas ("dada", "papa", etc.).","Se mantiene sentado y sin ayuda mientras juega","Utiliza "sus" palabras otorgándoles significado."]'),
	(111, 39, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño conoce y señala imágenes que ve."]'),
	(112, 40, 'ACCIONES DE CORTESÍA', '26', 'VidaFamilia', '[]'),
	(113, 40, 'ATRAPO LA BOTELLA', '126', 'JugandoAprendo', '["El niño/a se dirige a alcanzar la botella mientras mama la va empujando.","Explora el ambiente con confianza, según sus posibilidades.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc.","Se desplaza gateando."]'),
	(114, 40, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño conoce y señala imágenes que ve."]'),
	(115, 41, 'NUESTRAS CANCIONES', '22', 'VidaFamilia', '[]'),
	(116, 41, 'EL ARO SUBE Y BAJA', '132', 'JugandoAprendo', '["El niño/a Juega con el aro, subiéndolo y bajándolo.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura"]'),
	(117, 41, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
	(118, 42, 'NUESTRAS CANCIONES', '22', 'VidaFamilia', '[]'),
	(119, 42, 'ENCUENTRO EL JUGUETE QUE NO VEO', '133', 'JugandoAprendo', '["El niño/a Encuentra el juguete escondido debajo del pañuelo","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc.","Se mantiene sentado y sin ayuda mientras juega."]'),
	(120, 42, 'EL COLLAR Y EL RECIPIENTE', '134', 'JugandoAprendo', '["Introduce y saca el collar de un recipiente utilizando los dedos índice y pulgar.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se mantiene sentado y sin ayuda mientras juega.","Manipula diversos recipientes interesándose en el interior de estos (noción de contenido) a partir de su propio cuerpo y diversos objetos: introduce su cabeza en una caja para observar su contenido, se mete dentro de una canasta, etc."]'),
	(121, 42, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
	(122, 43, 'ME DIVIERTO CON LA MÚSICA', '27', 'VidaFamilia', '[]'),
	(123, 43, 'RUEDO EL TARRO', '135', 'JugandoAprendo', '["El niño/a rueda el tarro para que haga sonido y disfruta del mismo.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se para con apoyo.","Da algunos pasos hacia adelante con apoyo.","Escucha diversos sonidos e intenta imitarlos vocalizando con claridad dos sílabas ("dada", "papa", etc.)."]'),
	(124, 43, 'LIBRO DE TELA', '-1', 'CuentameCuento', '["Disfruta de canciones que mama le canta"]'),
	(125, 44, 'ME DIVIERTO CON LA MÚSICA', '27', 'VidaFamilia', '[]'),
	(126, 44, 'GATEO POR EL TÚNEL', '128', 'JugandoAprendo', '["Se desplaza gateando por el túnel.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Explora el ambiente con confianza según sus posibilidades.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se mete en cajas acomodando su cuerpo de acuerdo a sus posibilidades."]'),
	(127, 44, 'CANCIÓN', '0', 'CuentameCuento', '["El niño/a baila al compás de la música que mama le canta."]'),
	(128, 45, '¿DÓNDE ESTÁ MÍ…?', '28', 'VidaFamilia', '[]'),
	(129, 45, 'GATEO POR EL TÚNEL', '128', 'JugandoAprendo', '["El niño/a  Se desplaza gateando por el túnel.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Explora el ambiente con confianza, según sus posibilidades."]'),
	(130, 45, 'LOS OBJETOS- Libro 1', '256', 'CuentameCuento', '["El niño/a observa con atención y señala objetos."]'),
	(131, 46, 'DÉJAME INTENTARLO', '29', 'VidaFamilia', '[]'),
	(132, 46, 'ENCESTO LAS PELOTAS', '136', 'JugandoAprendo', '["Lanza objetos a distancia corta.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc","Hace rodar una pelota con ambas mano.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se mete en cajas acomodando su cuerpo de acuerdo a sus posibilidades"]'),
	(133, 46, '6 OBJETOS', '241', 'CuentameCuento', '[" El niño observa y nombra algunos objetos."]'),
	(134, 47, 'MI PLATO LLENO  Y DESPUÉS VACÍO', '30', 'VidaFamilia', '[]'),
	(135, 47, 'ENCUENTRO EL JUGUETE QUE NO VEO', '133', 'JugandoAprendo', '["Observa un objeto que se oculta debajo del pañuelo.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se mantiene sentado y sin ayuda mientras juega.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc."]'),
	(136, 47, 'MIS EMOCIONES – Libro 2', '257', 'CuentameCuento', '["El niño describe imágenes del cuento."]'),
	(137, 48, 'CUENTOS', '31', 'VidaFamilia', '[]'),
	(138, 48, 'JUEGO CON 6  CUBOS', '138', 'JugandoAprendo', '["El niño/a levanta el recipiente para encontrar el cubo que esta debajo del mismo.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Se mantiene sentado y sin ayuda mientras juega.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc.","Señala un objeto conocido cuando se lo nombra."]'),
	(139, 48, 'LAMINA 2: 9 OBJETOS - ', '242', 'CuentameCuento', '[" El  niño mira y conoce objetos."]'),
	(140, 49, 'CONTAR HISTORIAS INVENTADAS', '32', 'VidaFamilia', '[]'),
	(141, 49, 'COLOCO OBJETOS DENTRO DE LA BOTELLA', '139', 'JugandoAprendo', '["El niño coloca con precisión objetos dentro de la botella.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Imita acciones rutinarias que realiza el adulto (barrer, lavar, planchar, etc.)","Colabora colocando los objetos en su lugar cuanto se lo piden."]'),
	(142, 49, 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El  niño mira y conoce objetos."]'),
	(143, 50, 'CADA COSA EN SU LUGAR', '33', 'VidaFamilia', '[]'),
	(144, 50, 'EMPUJO  EL JUGUETE', '140', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
	(145, 50, 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce sus emociones."]'),
	(146, 51, 'LA BASURA TAMBIÉN TIENE SU LUGAR', '34', 'VidaFamilia', '[]'),
	(147, 51, 'ENCESTO LAS PELOTAS', '133', 'JugandoAprendo', '["Lanza la pelota hacia el recipiente desde una distancia corta.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
	(148, 51, 'EL TITERE APARECE Y DESAPARECE', '141', 'JugandoAprendo', '["El Niño/a busca el juguete escondido.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple."]'),
	(149, 51, 'LAMINA 1:6 OBJETOS', '241', 'CuentameCuento', '["El  niño mira y conoce objetos."]'),
	(150, 52, 'CUENTOS', '35', 'VidaFamilia', '[]'),
	(151, 52, 'JUEGO CON 4 CUBOS', '138', 'JugandoAprendo', '["Encuentra los cubos ocultos","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple"]'),
	(152, 52, 'LAMINA 2: 9 OBJETOS', '242', 'CuentameCuento', '["El niño conoce objetos  y para qué sirven"]'),
	(153, 53, 'DE LAS ACCIONES A LAS PALABRAS', '36', 'VidaFamilia', '[]'),
	(154, 53, 'ENCUENTRO  MI JUGUETE DEBAJO DEL PAÑUELO CORRECTO', '143', 'JugandoAprendo', '["Busca objetos totalmente ocultos","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(155, 53, 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El niño conoce objetos  y para qué sirven."]'),
	(156, 54, ' “HACER COMO SI …”', '37', 'VidaFamilia', '[]'),
	(157, 54, 'ME ESCONDO', '258', 'JugandoAprendo', '["Se desplaza por el espacio y reconoce cuando está dentro o afuera.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(158, 54, 'LIBRO 3:  LOS ANIMALES', '-2', 'CuentameCuento', '["El niño reconoce y nombra los animales que observa."]'),
	(159, 55, 'BAILAMOS', '38', 'VidaFamilia', '[]'),
	(160, 55, 'RUEDO EL TARRO DISTINTOS SUPERFICIES', '145', 'JugandoAprendo', '["Rueda el tarro en diferentes superficies siguiendo indicaciones de mamá.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(161, 55, 'LAMINA 1:6 OBJETOS', '241', 'CuentameCuento', '["El niño reconoce y nombra objetos."]'),
	(162, 56, 'LOS ALIMENTOS', '39', 'VidaFamilia', '[]'),
	(163, 56, 'ME ESCONDO', '144', 'JugandoAprendo', '["Se desplaza por el espacio y reconoce cuando está dentro o afuera","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota""]'),
	(164, 56, 'HAGO TORRES DE 6 CUBOS', '146', 'JugandoAprendo', '["Coloca los cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(165, 56, 'LAMINA 2 : NUEVE  OBJETOS', '242', 'CuentameCuento', '["El niño reconoce y nombra objetos, identificando para qué sirven."]'),
	(166, 57, '¿QUÉ HACEN LAS PERSONAS?', '40', 'VidaFamilia', '[]'),
	(167, 57, 'SONIDO… SILENCIO', '147', 'JugandoAprendo', '["El niño controla el movimiento de las maracas identificando el sonido y silencio.","Comprende el sentido del NO (p.e. detiene una acción cuando se le dice NO)."]'),
	(168, 57, 'HAGO TORRES CON SEIS CUBOS', '146', 'JugandoAprendo', '["Coloca los cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota".","Utiliza palabras o fragmentos de palabra para designar personas u objetos conocidos: "Tata" para indicar abuelo, "pan" cuando quiere pan, etc.","Señala un objeto conocido cuando se lo nombra (10-12 m)","Utiliza "sus" palabras otorgándoles significado  (10-12 m)."]'),
	(169, 57, 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El niño reconoce y nombra  objetos."]'),
	(170, 58, 'NUESTRAS DANZAS', '41', 'VidaFamilia', '[]'),
	(171, 58, 'ENCAJO EL VASO PEQUEÑO DENTRO DEL MAS GRANDE', '148', 'JugandoAprendo', '["Encaja el vaso pequeño dentro del vaso grande.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Intenta hacer cosas por sí mismo (ej. Intenta guardar los juguetes, abrocharse el abrigo aunque no lo logre, quitarse la ropa, abrir el lavamanos, manejar la cuchara, beber de una taza, etc.).","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
	(172, 58, 'EMPUJO EL JUGUETE', '140', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Utiliza palabras o fragmentos de palabra para designar personas u objetos conocidos: "Tata" para indicar abuelo, "pan" cuando quiere pan, etc.","Señala un objeto conocido cuando se lo nombra (10-12 m).","Utiliza "sus" palabras otorgándoles significado  (10-12 m)."]'),
	(173, 58, 'LAMINA 2 : NUEVE  OBJETOS', '242', 'CuentameCuento', '["El niño aprende el nombre de los objetos y para qué sirven."]'),
	(174, 59, 'CARITA REDONDA', '42', 'VidaFamilia', '[]'),
	(175, 59, 'LLENAMOS TODAS LAS BOTELLAS', '149', 'JugandoAprendo', '["Llena la botella con mucha precisión haciendo uso de objetos de diferente tamaño.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple"]'),
	(176, 59, 'LAMINA  3:DOCE  OBJETOS', '243', 'CuentameCuento', '["El niño reconoce animales y objetos  de su entorno."]'),
	(177, 60, 'ESPEJITO ESPEJITO', '43', 'VidaFamilia', '[]'),
	(178, 60, 'ROMPECABEZAS 1', '150', 'JugandoAprendo', '["Encaja las piezas del rompe cabezas.","-Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
	(179, 60, 'LIBRO 3 : LOS ANIMALES', '258', 'CuentameCuento', '["El niño escucha y reconoce sonidos de los animales de su entorno."]'),
	(180, 61, '¿QUÉ HACEN LAS PERSONAS?', '40', 'VidaFamilia', '[]'),
	(181, 61, 'ENSARTO LOS AROS', '151', 'JugandoAprendo', '["Ensarta los aros en el tubo siguiendo indicaciones de mama.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
	(182, 61, 'HAGO TORRES CON OCHO CUBOS', '152', 'JugandoAprendo', '["Coloca 08 cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(183, 61, 'LAMINA 3:DOCE OBJETOS', '243', 'CuentameCuento', '["El niño reconoce y menciona  animales y objetos de su entorno."]'),
	(184, 62, 'NUESTRAS DANZAS', '41', 'VidaFamilia', '[]'),
	(185, 62, 'ARRASTRO EL GUSANO', '153', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc. Jalando el gusanito.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(186, 62, 'ENSARTO  LOS AROS', '151', 'JugandoAprendo', '["Ensarta los aros en el tubo con precisión siguiendo indicaciones de mama.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
	(187, 62, 'LAMINA 2 : NUEVE  OBJETOS', '242', 'CuentameCuento', '["El niño conoce y mencionan  objetos y para qué sirven."]'),
	(188, 63, 'CARITA REDONDA', '42', 'VidaFamilia', '[]'),
	(189, 63, 'JALO EL COLECTIVO', '154', 'JugandoAprendo', '["Imita sonidos de animales y objetos que conoce):  guau, titi, etc","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: Césped, arena, etc.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(190, 63, 'ARRASTRO EL GUSANO', '153', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc. Jalando el gusanito ","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(191, 63, 'LIBRO  3 : LOS ANIMALES', '248', 'CuentameCuento', '["El niño escucha y conoce sonidos de los animales de su entorno."]'),
	(192, 64, 'ESPEJITO ESPEJITO', '43', 'VidaFamilia', '[]'),
	(193, 64, 'CUIDO AL BEBE Y RECONOZCO LAS PARTES DEL CUERPO', '155', 'JugandoAprendo', '["Reconoce y señala  partes de su cuerpo y de otra persona.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(194, 64, 'ME ESCONDO', '144', 'JugandoAprendo', '["Se desplaza por el espacio y reconoce cuando está dentro o afuera ","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota".","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple."]'),
	(195, 64, 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce sus  emociones."]'),
	(196, 65, '¿QUÉ HACEN LAS PERSONAS?', '40', 'VidaFamilia', '[]'),
	(197, 65, 'MI JUGUETE DEBAJO DE LOS PAÑUELOS', '156', 'JugandoAprendo', '["El niño busca los juguetes debajo de los pañuelos","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(198, 65, 'HAGO TORRES CON OCHO CUBOS', '152', 'JugandoAprendo', '["Coloca 08 cubos uno encima de otro","Señala un objeto conocido cuando se lo nombra (10-12 m)","Utiliza "sus" palabras otorgándoles significado  (10-12 m)","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(199, 65, 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El niño conoce y nombra  objetos."]'),
	(200, 66, 'NUESTRAS DANZAS', '41', 'VidaFamilia', '[]'),
	(201, 66, 'RUEDO LAS PELOTAS POR EL TUBO', '157', 'JugandoAprendo', '["Realiza movimientos de mayor precisión con sus manos.  P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: Césped, arena, etc."]'),
	(202, 66, 'ROMPECABEZAS 2', '158', 'JugandoAprendo', '["El niño encaja las piezas del rompe cabezas","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos.","Mantiene la atención cuando le narran cuentos muy cortos."]'),
	(203, 66, 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce emociones a través de diversos gestos."]'),
	(204, 67, 'CARITA REDONDA', '42', 'VidaFamilia', '[]'),
	(205, 67, 'ENCAJO EL CUBO PEQUEÑO DENTRO DEL GRANDE', '159', 'JugandoAprendo', '["Encaja el vaso pequeño dentro del vaso grande.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Intenta hacer cosas por sí mismo (ej. Intenta guardar los juguetes, abrocharse el abrigo aunque no lo logre, quitarse la ropa, abrir el lavamanos, manejar la cuchara, beber de una taza, etc.)"]'),
	(206, 67, 'ENCESTO LAS PELOTAS', '136', 'JugandoAprendo', '["El niño lanza la pelota hacia el cesto desde una distancia corta","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: Césped, arena, etc.","Lanza objetos a distancia corta (10-12 m)."]'),
	(207, 67, 'LAMINA :2 NUEVE OBJETOS', '242', 'CuentameCuento', '[" El niño aprende el nombre de los objetos y para qué sirven."]'),
	(208, 68, 'ESPEJITO ESPEJITO', '43', 'VidaFamilia', '[]'),
	(209, 68, 'EMPUJO EL JUGUETE HACIENDO ”VRUM”', '160', 'JugandoAprendo', '["Imita sonidos de animales y objetos que conoce:  guau, titi, etc","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: césped, arena, etc.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación "dame la pelota"."]'),
	(210, 68, 'ROMPECABEZAS 2', '158', 'JugandoAprendo', '["Encaja las piezas del rompecabezas.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Pasa páginas gruesas de un libro 2 ó 3 a la vez.","Mantiene la atención cuando le narran cuentos"]'),
	(211, 68, 'LIBRO 3 :LOS ANIMALES', '258', 'CuentameCuento', '["El niño escucha y conoce sonidos de los animales de su entorno."]'),
	(212, 69, 'FUERA DEL PAÑAL', '44', 'VidaFamilia', '[]'),
	(213, 69, 'ARRIBA LAS MARACAS', '161', 'JugandoAprendo', '["El niño imita los movimientos que hace mama usando las marcas y se divierte con ellas moviéndola en diferentes direcciones.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
	(214, 69, 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce emociones a través de diversos gestos "]'),
	(215, 70, 'CONOZCO LAS PARTES  DE MI CUERPO', '45', 'VidaFamilia', '[]'),
	(216, 70, 'COLOCA  Y SACA TODOS LOS OBJETOS DE LA BOTELLA', '162', 'JugandoAprendo', '["El niño coloca objetos diferentes en la botella cuando su mama le indica.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
	(217, 70, 'LAMINA 3 : DOCE OBJETOS', '243', 'CuentameCuento', '[" El niño reconoce los animales y objetos de su entorno."]'),
	(218, 71, 'CADA  PARTE HACE ALGO', '46', 'VidaFamilia', '[]'),
	(219, 71, 'ENCAJO DOS CUBOS Y DOS VASOS LÓGICOS', '163', 'JugandoAprendo', '["El niño encaja el cubo chico en el cubo grande y el vaso chico en el vaso grande.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Intenta hacer cosas por sí mismo (ej. Intenta guardar los juguetes, abrocharse el abrigo aunque no lo logre, quitarse la ropa, abrir el lavamanos, manejar la cuchara, beber de una taza, etc.)"]'),
	(220, 71, 'ROMPECABEZAS 2 FLORES EN UNA MACETA', '158', 'JugandoAprendo', '["Encaja las piezas del rompe cabezas","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
	(221, 71, 'LIBRO 4: EL BEBE TIENE HAMBRE', '259', 'CuentameCuento', '["El niño escucha historias sencillas de la vida cotidiana."]'),
	(222, 72, 'IGUALES Y DIFERENTES', '47', 'VidaFamilia', '[]'),
	(223, 72, 'JALO EL GUSANO HACIA MI', '164', 'JugandoAprendo', '["Resuelve problemas utilizando sus experiencias previas","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan"]'),
	(224, 72, 'LIBRO 3 :LOS ANIMALES', '258', 'CuentameCuento', '["El niño escucha y reconoce sonidos de los animales de su entorno."]'),
	(225, 73, 'IGUALES  Y DIFERENTES', '47', 'VidaFamilia', '[]'),
	(226, 73, 'LANZO LAS ALMOHADAS', '165', 'JugandoAprendo', '["Lanza las almohadas hacia el cesto.","Diferencia características notorias entre los objetos: grande-pequeño, duro-blando, frío-caliente"]'),
	(227, 73, 'LAMINA 4 : QUINCE OBJETOS', '244', 'CuentameCuento', '["El niño nombra los alimentos que ve."]'),
	(228, 74, 'LO QUE ES IGUAL LO PONEMOS JUNTO', '48', 'VidaFamilia', '[]'),
	(229, 74, 'ROMPECABEZAS 3:', '166', 'JugandoAprendo', '["Encaja las piezas del rompecabezas","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Reconoce objetos cotidianos y significativos en ilustraciones"]'),
	(230, 74, 'LIBRO 5 : EL POLO SUCIO', '260', 'CuentameCuento', '["El niño escucha una historia sobre  limpio, sucio y mojado."]'),
	(231, 75, 'ESTO ES GRANDE  Y ESTO ES PEQUEÑO', '49', 'VidaFamilia', '[]'),
	(232, 75, 'MIS CARRITOS “VRUM, VRUM”', '167', 'JugandoAprendo', '["Imita el sonido de los carritos mientras juega con ellos.","Juega cerca a otros niños realizando acciones similares o utilizando materiales","Imita sonidos onomatopéyicos (de animales y objetos que conoce): guau, guau, titi, etc. (13-18 m)"]'),
	(233, 75, 'Â¿CÃ“MO HACEN LOS ANIMALES?', '168', 'JugandoAprendo', '["Imita el sonido que hace los animales que Ã©l conoce."," Imita sonidos onomatopÃ©yicos (de animales y objetos que conoce): guau, guau, titi, etc. (13-18 m)","Se mantiene sentado y sin apoyo mientras juega (10-12 m"]'),
	(234, 75, 'LAMINA 3 : DOCE OBJETOS', '243', 'CuentameCuento', '["El niÃ±o reconoce  caracterÃ­sticas  de los animales y objetos de su entorno."]'),
	(235, 76, 'DIGO EL NOMBRE DE LOS ALIMENTOS', '50', 'VidaFamilia', '[]'),
	(236, 76, 'PASEO EN EL COLECTIVO', '169', 'JugandoAprendo', '["El niÃ±o representa actividades de su vida diaria jugando en el colectivo","Realiza movimientos de mayor precisiÃ³n con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, , troza con ambas manos","Encaja varias piezas en un tablero, adecuando sus manos y dedos"]'),
	(237, 76, 'ROMPECABEZAS 3', '166', 'JugandoAprendo', '["El niÃ±o encaja las piezas del rompecabezas.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Reconoce objetos cotidianos y significativos en ilustraciones"]'),
	(238, 76, 'HAGO UNA FILA DE CUBOS', '170', 'JugandoAprendo', '["El niÃ±o hace una fila con los cubos y lo empuja hacia adelante.","Juega representando actividades de la vida cotidiana (da de comer a la muÃ±eca, maneja el carro, carga la wawa en la lliclla, etc) utilizando objetos diversos para completar sus juegos de imitaciÃ³n."]'),
	(239, 76, 'LIBRO 2 MIS EMOCIONES', '257', 'CuentameCuento', '["El niÃ±o reconoce emociones a travÃ©s de diversos gestos."]'),
	(240, 77, 'DIGO LAS CARACTERÃSTICAS DE LOS ALIMENTOS', '51', 'VidaFamilia', '[]'),
	(241, 77, 'MI JUGUETE EN EL PUÃ‘O DE LA MAMA', '171', 'JugandoAprendo', '["El niÃ±o busca la mano de su mama, que estÃ¡ escondido debajo del paÃ±uelo.","Muestra interÃ©s e iniciativa en la relaciÃ³n con los adultos, repitiendo acciones que le agradan.","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo","Comprende indicaciones sencillas realizando la acciÃ³n: entrega la pelota ante la indicaciÃ³n "dame la pelota", busca la mano ante la indicaciÃ³n "bÃºscala", etc. (13-18 m)."]'),
	(242, 77, 'LIBRO 1 : POLO SUCIO', '260', 'CuentameCuento', '["El niÃ±o escucha una historia sobre limpio, sucio y mojado."]'),
	(243, 78, 'LOS ALIMENTOS TIENEN COLOR', '52', 'VidaFamilia', '[]'),
	(244, 78, 'ME DIVIERTO JALANDO EL GUSANITO', '162', 'JugandoAprendo', '["Corre en distintas direcciones jalando el gusanito.","Jala los objetos de un lugar a otro."]'),
	(245, 78, 'LIBRO  6 :VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niÃ±o escucha una historia de la vida cotidiana"]'),
	(246, 79, 'ME AYUDAS A BARRER', '53', 'VidaFamilia', '[]'),
	(247, 79, 'LOS ANIMALES HACEN UNA FILA', '173', 'JugandoAprendo', '["El niÃ±o coloca a los animales uno al lado de otro mencionando su nombre.","Pregunta el nombre de los objetos que acaba de conocer y los repite","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo."]'),
	(248, 79, 'Â¿A DÃ“NDE SE FUERON LOS ANIMALES?', '173', 'JugandoAprendo', '["Busca los animales, cuando su mama lo esconde."]'),
	(249, 79, 'LAMINA 3 : DOCE OBJETOS', '243', 'CuentameCuento', '["El niÃ±o reconoce los animales y objetos  de su entorno."]'),
	(250, 80, 'ME AYUDAS A LIMPIAR', '54', 'VidaFamilia', '[]'),
	(251, 80, 'CUIDO AL BEBE Y APRENDO LAS PARTES DEL CUERPO', '155', 'JugandoAprendo', '["Reconoce las partes gruesas y finas de su cuerpo","Demuestra sentido rÃ­tmico moviÃ©ndose espontÃ¡neamente ante la mÃºsica."]'),
	(252, 80, 'ROMPECABEZAS 3', '166', 'JugandoAprendo', '["El niÃ±o encaja las piezas del rompecabezas.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Reconoce objetos cotidianos y significativos en ilustraciones"]'),
	(253, 80, 'LIBRO 5 : Ã‰L BEBE TIENE HAMBRE', '-3', 'CuentameCuento', '["El niÃ±o escucha una historia "]'),
	(254, 81, 'MI CUERPO SE ESTÃ MOVIENDO', '55', 'VidaFamilia', '[]'),
	(255, 81, 'ENCUENTRO MI JUGUETE DEBAJO DE  PAÃ‘UELOS ARRUGADOS', '174', 'JugandoAprendo', '["Busca objetos conocidos aunque no los tenga a la vista.","Resuelve problemas utilizando sus experiencias previas."]'),
	(256, 81, 'LAMINA  4: 15 OBJETOS', '244', 'CuentameCuento', '["El niÃ±o menciona caracterÃ­sticas y utilidad de los alimentos."]'),
	(257, 82, 'CUANDO ME ASEO  APRENDO MÃS PARTES DE MI CUERPO', '56', 'VidaFamilia', '[]'),
	(258, 82, 'ENCAJO  TODOS LOS CUBOS Y LOS VASOS LÃ“GICOS', '175', 'JugandoAprendo', '["El niÃ±o encaja todos los cubos y vasos lÃ³gicos.","Realiza movimientos de mayor precisiÃ³n con sus manos. P.e.: abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
	(259, 82, 'ROMPECABEZAS  4', '177', 'JugandoAprendo', '["Encaja las piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
	(260, 82, 'LIBRO  5: EL POLO SUCIO', '260', 'CuentameCuento', '["El niÃ±o escucha una historia sobre limpio, sucio y mojado.."]'),
	(261, 83, 'MI ROPA TIENE COLOR', '57', 'VidaFamilia', '[]'),
	(262, 83, 'EL COLECTIVO AVANZA Y SE DETIENE', '176', 'JugandoAprendo', '["El niÃ±o jala el colectivo en diferentes direcciones.","Diferencia caracterÃ­sticas notorias entre los objetos: grande-pequeÃ±o, duro-blando, frÃ­o-caliente.","Juega representando actividades de la vida cotidiana (da de comer a la muÃ±eca, maneja el carro, carga la wawa en la lliclla, etc.) utilizando objetos diversos para completar sus juegos de imitaciÃ³n."]'),
	(263, 83, 'LIBRO 4: EL BEBE TIENE HAMBRE', '259', 'CuentameCuento', '[" El niÃ±o escucha historias de la vida cotidiana."]'),
	(264, 84, 'Â¿ESTÃ LLENO O VACÃO?', '58', 'VidaFamilia', '[]'),
	(265, 84, 'RUEDO LAS PELOTAS POR EL TUBO', '157', 'JugandoAprendo', '["El niÃ±o hace rodar la pelota por el tubo inclinado."]'),
	(266, 84, 'ROMPECABEZAS 4', '177', 'JugandoAprendo', '["Encaja piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
	(267, 84, 'LIBRO 6: VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niÃ±o  escucha  una historia sobre la vida cotidiana."]'),
	(268, 85, 'ENCUENTRO TESOROS POR DONDE CAMINO', '59', 'VidaFamilia', '[]'),
	(269, 85, 'EXPERIMENTANDO CON NOCIONES â€œENCIMA  Y DEBAJOâ€', '178', 'JugandoAprendo', '["El niÃ±o coloca encima o debajo  de la mesa.","Muestra interÃ©s e iniciativa en la relaciÃ³n con los adultos, repitiendo acciones que le agradan.","Comprende indicaciones sencillas realizando la acciÃ³n:  Entrega la pelota ante la indicaciÃ³n "dame la pelota", empuja el juguete, etc. (13-18 m)"]'),
	(270, 85, 'LIBRO 4: Ã‰L BEBE TIENE HAMBRE', '259', 'CuentameCuento', '["El niÃ±o  escucha  una historia sobre la vida cotidiana."]'),
	(271, 86, 'SIMÃ“N DICEâ€¦', '60', 'VidaFamilia', '[]'),
	(272, 86, 'LOS ANIMALES  HACEN UNA FILA', '173', 'JugandoAprendo', '["El niÃ±o coloca a los animales uno al lado de otro mencionando su nombre.","Pregunta el nombre de los objetos que acaba de conocer y los repite."]'),
	(273, 86, 'ROMPECABEZAS  4', '177', 'JugandoAprendo', '["Encaja las piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
	(274, 86, 'LAMINA 3:12 OBJETOS', '243', 'CuentameCuento', '["El niÃ±o reconozca  los animales y objetos  de su entorno."]'),
	(275, 87, 'OTRO SIMÃ“N DICE â€¦', '61', 'VidaFamilia', '[]'),
	(276, 87, 'CAMINO SIN  CHOCARME', '179', 'JugandoAprendo', '["El niÃ±o camina entre las almohadas sin chocarse","Juega representando actividades de la vida cotidiana (da de comer a la muÃ±eca, maneja el carro, carga la wawa en la lliclla, etc.) utilizando objetos diversos para completar sus juegos de imitaciÃ³n."]'),
	(277, 87, 'JUEGO CON LOS BLOQUES  DE DIFERENTES  FORMAS', '180', 'JugandoAprendo', '["El niÃ±o diferencia el bloque segÃºn su tamaÃ±o.","Juega representando actividades de la vida cotidiana (da de comer a la muÃ±eca, maneja el carro, carga la wawa en la lliclla, etc.) utilizando objetos diversos para completar sus juegos de imitaciÃ³n."]'),
	(278, 87, 'LAMINA 4: 15 ALIMENTOS', '244', 'CuentameCuento', '["El niÃ±o menciona    las caracterÃ­sticas   de los alimentos."]'),
	(279, 88, 'LLAMEMOS A â€¦', '62', 'VidaFamilia', '[]'),
	(280, 88, 'ENCESTO LAS PELOTAS', '136', 'JugandoAprendo', '["Lanza la pelota hacia una direcciÃ³n determinada","Lanza objetos a distancia corta (10-12 m"]'),
	(281, 88, 'ROMPECABEZAS 4', '177', 'JugandoAprendo', '["Encaja piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
	(282, 88, 'JUEGO CON DIEZ CUBOS', '181', 'JugandoAprendo', '["Coloca cubos uno encima de otro","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m)"]'),
	(283, 88, 'LIBRO 5: EL POLO SUCIO', '260', 'CuentameCuento', '["El niÃ±o escucha  una historia sobre limpio, sucio y mojado."]'),
	(284, 89, 'VEO, VEO.', '63', 'VidaFamilia', '[]'),
	(285, 89, 'EL  COLECTIVO VA LEJOS Y DEJA A TODOS LOS PASAJEROS', '182', 'JugandoAprendo', '["El niÃ±o representa actividades de su vida diaria jugando con el carrito.","Jala los objetos de un lugar a otro."]'),
	(286, 89, 'LAMINA 4: 15 OBJETOS', '244', 'CuentameCuento', '["El niÃ±o menciona  las caracterÃ­sticas de  animales."]'),
	(287, 90, 'VEO, VEO', '63', 'VidaFamilia', '[]'),
	(288, 90, 'ROMPECABEZAS 5', '183', 'JugandoAprendo', '["Encaja las piezas del rompecabezas","Diferencia caracterÃ­sticas notorias entre los objetos: grande-pequeÃ±o, duro-blando, frÃ­o-caliente"]'),
	(289, 90, 'EL POLO SUCIO', '260', 'CuentameCuento', '["El niÃ±o sigue la secuencia  de la historia reconociendo  limpio, sucio y mojado."]'),
	(290, 91, 'MI BANDA', '64', 'VidaFamilia', '[]'),
	(291, 91, 'SOY FUERTE', '184', 'JugandoAprendo', '["El niÃ±o identifica la diferencia entre pesado y liviano","Camina manteniendo el equilibrio sobre diferentes planos sin caerse:  Inclinado, ondulado, etc."]'),
	(292, 91, 'JUEGO CON DIEZ CUBOS', '181', 'JugandoAprendo', '["Coloca cubos uno encima de otro","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m)"]'),
	(293, 91, 'LIBRO 6:VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niÃ±o  nombra los alimentos mÃ¡s comunes  y las acciones de ir a comprarlos."]'),
	(294, 92, 'MI BANDA', '64', 'VidaFamilia', '[]'),
	(295, 92, 'ME  DIVIERTO JALANDO EL GUSANITO RÃPIDO Y LENTO', '185', 'JugandoAprendo', '["Corre en distintas direcciones jalando el gusanito.","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m)"]'),
	(296, 92, 'ROMPECABEZAS 6', '186', 'JugandoAprendo', '["Coloca cubos uno encima de otro","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo.","Comprende indicaciones sencillas realizando la accion (13-18 m)"]'),
	(297, 92, 'LIBRO 4: EL BEBE TIENE HAMBRE', '259', 'CuentameCuento', '["El niÃ±o escucha historias y describe las situaciones  del  cuento."]'),
	(298, 93, 'JUGAMOS A BAÃ‘AR LOS MUÃ‘ECOS', '65', 'VidaFamilia', '[]'),
	(299, 93, 'DERRUMBO LA PARED', '187', 'JugandoAprendo', '["Lanza un objeto hacia la pared de cubos para derrumbarla.","Realiza movimientos de mayor precisiÃ³n con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos"]'),
	(300, 93, 'TÃTERE CONVERSADOR', '188', 'JugandoAprendo', '["Se expresa por medio de frases de dos o tres palabras.","Conoce algunas reglas bÃ¡sicas aunque no siempre las sigue (p.e.: no empujar al amigo, esperar su turno, guardar al terminar de jugar)","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo"]'),
	(301, 93, 'ESCENA 1: LA POSTA MEDICA', '245', 'CuentameCuento', '["El niÃ±o reconoce las acciones realizadas en una posta mÃ©dica y quienes trabajan ahÃ­."]'),
	(302, 94, 'GRANDE  PEQUEÃ‘O', '66', 'VidaFamilia', '[]'),
	(303, 94, 'HACEMOS UN SOBRE', '189', 'JugandoAprendo', '["Garabetea libremente.","Realiza movimientos de mayor precisiÃ³n con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos"]'),
	(304, 94, 'Â¿DÃ“NDE ESTÃ MI  CARRO?', '190', 'JugandoAprendo', '["El niÃ±o representa actividades de su vida diaria jugando con el carrito.","Se desplaza por el espacio reconociendo la ubicaciÃ³n de los objetos (sabe dÃ³nde se guardan los juguetes, arriba-abajo la ubicaciÃ³n de los muebles)."]'),
	(305, 94, 'LIBRO 6: VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niÃ±o  nombra los alimentos mÃ¡s comunes y las acciones de ir a comprarlos."]'),
	(306, 95, 'ESTO USA PAPA  Y ESTO USA MAMA', '67', 'VidaFamilia', '[]'),
	(307, 95, 'JUEGO  A COSTAR AL  BEBE', '191', 'JugandoAprendo', '["El niÃ±o representa actividades de su vida diaria jugando con el muÃ±eco.","Reconoce las partes gruesas y finas de su cuerpo"]'),
	(308, 95, 'LOTERÃA  1: LA FLOR DE TAPAS', '192', 'JugandoAprendo', '["Agrupa objetos iguales.","Reconoce objetos cotidianos y significativos en ilustraciones."]'),
	(309, 95, 'LIBRO 7: MI DÃA', '262', 'CuentameCuento', '["El niÃ±o identifica y reconoce las actividades que se realizan durante el dÃ­a."]'),
	(310, 96, 'Â¿QUÃ‰ RARO?', '68', 'VidaFamilia', '[]'),
	(311, 96, 'LA FLOR DE TAPAS', '193', 'JugandoAprendo', '["Resuelve problemas utilizando sus experiencias previas","Realiza movimientos de mayor precisiÃ³n con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
	(312, 96, 'ROMPECABEZAS 7', '194', 'JugandoAprendo', '["Encaja varias piezas en un tablero adecuando sus manos y dedos.","Reconoce las partes gruesas y finas de su cuerpo","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo."]'),
	(313, 96, 'ESCENA 2:LA CHACRA', '246', 'CuentameCuento', '["El niÃ±o describe actividades que realiza su familia en la chacra."]'),
	(314, 97, 'CONOZCO LOS NOMBRES DE LAS PRENDAS DE VESTIR', '69', 'VidaFamilia', '[]'),
	(315, 97, 'HAGO UN COLLAR', '195', 'JugandoAprendo', '["Ensarta cuentas con orificios grandes.","Realiza movimientos de mayor precisiÃ³n con sus dedos. P.e. abotona, desabotona, abrocha, desabrocha, sube y baja cierres, rasga con los dedos, abolilla, inserta objetos en ranura."]'),
	(316, 97, 'JUEGO CON LOS BLOQUES  DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m).","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
	(317, 97, 'MIS PRIMEROS  DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
	(318, 97, 'ESCENA 3: LA PLAZA PRINCIPAL /LA PESCA', '274', 'CuentameCuento', '["La mamÃ¡ le cuente una historia de la plaza de su pueblo al niÃ±o."]'),
	(319, 98, 'Â¿QUÃ‰ COSAS  FALTAN?', '70', 'VidaFamilia', '[]'),
	(320, 98, 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
	(321, 98, 'TÃTERE CONVERSADOR', '188', 'JugandoAprendo', '["Se expresa utilizando frases de 2 o 3  palabras","Sigue reglas bÃ¡sicas: Guardar juguetes, pasar de un espacio a otro cuando se le indique, no pegar al otro, etc."]'),
	(322, 98, 'ESCENA 1: LA POSTA MEDICA', '245', 'CuentameCuento', '["El niÃ±o escucha y relaciona el relato de la posta medica"]'),
	(323, 99, 'Â¿QUÃ‰ SERÃ?', '71', 'VidaFamilia', '[]'),
	(324, 99, 'EL COLECTIVO VA LEJOS  Y DEJA A TODOS LOS PASAJEROS', '182', 'JugandoAprendo', '["El niÃ±o representa actividades de su vida diaria jugando con el carrito.","Dramatiza situaciones conocidas, que contienen pequeÃ±os argumentos."]'),
	(325, 99, 'LOTERÃA 1: LA FLOR DE TAPAS', '193', 'JugandoAprendo', '["Resuelve problemas utilizando sus experiencias previas","Nombra objetos familiares que observa en ilustraciones"]'),
	(326, 99, 'ROMPECABEZAS  7', '194', 'JugandoAprendo', '["Encaja varias piezas en un tablero adecuando sus manos y dedos.","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m)"]'),
	(327, 99, 'LIBRO 7: MI DÃA', '262', 'CuentameCuento', '["El niÃ±o reconoce y asocia las rutinas del dÃ­a."]'),
	(328, 100, 'Â¿QUÃ‰  SERÃ? ', '76', 'VidaFamilia', '[]'),
	(329, 100, 'JUEGO LA COMIDITA', '198', 'JugandoAprendo', '["Dramatiza situaciones conocidas de vida diaria jugando a la comidita","Colabora con iniciativa en tareas sencillas: guardar juguetes, botar basura, poner platos en la mesa, etc.","Relaciona objetos segÃºn su funciÃ³n: peine para peinarse, taza para tomar, etc."]'),
	(330, 100, 'ROMPECABEZAS 7', '194', 'JugandoAprendo', '["Encaja varias piezas en un tablero adecuando sus manos y dedos.","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo."]'),
	(331, 100, 'LIBRO 8: A MARÃA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niÃ±o asocia las escena con su vida cotidiana"]'),
	(332, 101, 'RECORDANDO LO QUE HICE HOY', '72', 'VidaFamilia', '[]'),
	(333, 101, 'CONSTRUYO CORRALES  PARA LOS ANIMALES', '199', 'JugandoAprendo', '["Utiliza diferentes objetos para hacer un corral para los animales","Mantiene la atenciÃ³n cuando le narra cuentos muy cortos (13-18 m)"]'),
	(334, 101, 'LIBRO 8: A MARÃA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niÃ±o asocia las escenas con su vida cotidiana."]'),
	(335, 102, 'RECORDANDO LO QUE HICE HOY', '72', 'VidaFamilia', '[]'),
	(336, 102, 'MIS CARROS VAN Y VAN', '200', 'JugandoAprendo', '["Dramatiza situaciones conocidas de vida diaria jugando  con el carrito","Diferencia caracterÃ­sticas notorias entre objetos: grande-pequeÃ±o (19-24 m)."]'),
	(337, 102, 'MIS  PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(338, 102, 'EXPERIMENTO CON LA CRAYOLA', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(339, 102, 'ESCENA 1: LA POSTA MEDICA', '245', 'CuentameCuento', '["El niÃ±o escucha y relaciona el relato de la posta medica"]'),
	(340, 103, 'Â¿DÃA, TARDE  O NOCHE?', '73', 'VidaFamilia', '[]'),
	(341, 103, 'LA CASITA DE TAPAS', '201', 'JugandoAprendo', '["Realiza movimientos de mayor precisiÃ³n con sus manos para armar una casita  con tapas.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(342, 103, 'LOTERÃA 2: MUEBLES', '202', 'JugandoAprendo', '["Coloca figuras que corresponden en la lÃ¡mina ","Agrupa objetos iguales (19-24 m)"]'),
	(343, 103, 'LIBRO 9 JUAN PREGUNTA Â¿CÃ“MO ES', '264', 'CuentameCuento', '["El niÃ±o escucha las explicaciones y el Â¿Por quÃ©? de las cosas."]'),
	(344, 104, 'Â¿DÃA, TARDE O NOCHE?', '73', 'VidaFamilia', '[]'),
	(345, 104, 'ROMPECABEZAS 8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(346, 104, 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(347, 104, 'ESCENA 2: LA CHACRA', '246', 'CuentameCuento', '["El niÃ±o escucha y relaciona el relato de la chacra de lo que realiza papÃ¡ y mamÃ¡."]'),
	(348, 105, 'AYUDO  A TENER LIMPIA MI ROPITA', '74', 'VidaFamilia', '[]'),
	(349, 105, 'JUEGO CON Ã‰L BEBE  Y HABLO SOBRE LAS PRENDAS DE  VESTIR', '204', 'JugandoAprendo', '["Dramatiza situaciones de su vida diaria, mientras juega con el muÃ±eco","Realiza movimientos de mayor precisiÃ³n con sus dedos. P.e. abotona, desabotona, abrocha, desabrocha, sube y baja cierres, rasga con los dedos, abolilla, insera objetos en ranuras"]'),
	(350, 105, 'JUEGO CON LOS BLOQUES DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego.","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m).","Se expresa por medio de frases de dos o tres palabras (19-24 m)"]'),
	(351, 105, 'LIBRO 7: MI DÃA', '262', 'CuentameCuento', '["El niÃ±o reconoce y asocia las rutinas del dÃ­a."]'),
	(352, 106, 'AYUDO A TENER LIMPIA MI ROPITA', '74', 'VidaFamilia', '[]'),
	(353, 106, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(354, 106, 'LIBRO 8: A MARÃA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niÃ±o asocia las escena con su vida cotidiana"]'),
	(355, 107, 'AYUDO A ORDENAR LA ROPA', '75', 'VidaFamilia', '[]'),
	(356, 107, 'LOTERÃA  2', '202', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos.","Agrupa objetos iguales (19-24 m)"]'),
	(357, 107, 'ESCENA 3: LA PLAZA PRINCIPAL/LA PESCA', '247', 'CuentameCuento', '["Que la mamÃ¡ le cuente una historia de la plaza de su pueblo."]'),
	(358, 108, 'AYUDO A ORDENAR LA ROPA', '75', 'VidaFamilia', '[]'),
	(359, 108, 'JUEGO  A LA COMIDITA', '198', 'JugandoAprendo', '["Dramatiza situaciones conocidas de su vida diaria jugando a la comidita","Colabora con iniciativa en tareas sencillas: guarda juguetes, botar la basura, poner platos en la mesa, etc.","Relaciona objetos segÃºn su funciÃ³n: peine para peinarse, taza para tomar, etc."]'),
	(360, 108, 'ROMPECABEZAS  8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(361, 108, 'LIBRO 9: JUAN PREGUNTA Â¿CÃ“MO ES?', '264', 'CuentameCuento', '["El niÃ±o escuche las explicaciones y el Â¿Por quÃ©? De las cosas."]'),
	(362, 109, 'Â¿ESTO ES TUYO?', '76', 'VidaFamilia', '[]'),
	(363, 109, 'HAGO UN COLLAR DE COLORES', '205', 'JugandoAprendo', '["Ensarta cuentas en con orificios pequeÃ±os."]'),
	(364, 109, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(365, 109, 'JUAN PREGUNTA Â¿CÃ“MO ES?', '264', 'CuentameCuento', '["El niÃ±o escucha las explicaciones y el Â¿Por quÃ©? de las cosas."]'),
	(366, 110, 'Â¿ESTO ES TUYO?', '76', 'VidaFamilia', '[]'),
	(367, 110, 'Â¿QUÃ‰ HAY  DENTRO DE LA BOLSA?', '206', 'JugandoAprendo', '["Sigue indicaciones de la mama  mientras juega."]'),
	(368, 110, 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
	(369, 110, 'ESCENA 4: LA FIESTA PATRONAL', '248', 'CuentameCuento', '["El niÃ±o escucha y relaciona el relato de la fiesta patronal."]'),
	(370, 111, 'AYUDO A COCINAR', '77', 'VidaFamilia', '[]'),
	(371, 111, 'MIS CARROS VAN Y VAN', '202', 'JugandoAprendo', '["El niÃ±o diferencia el carro grande y el carro pequeÃ±o."]'),
	(372, 111, 'LOTERÃA 3: 6 OBJETOS FAMILIARES', '208', 'CuentameCuento', '["Encaja varias piezas en un tablero, segÃºn la lÃ¡mina.","Relaciona objetos segÃºn su funciÃ³n: peine para peinarse, taza para tomar, etc.","Agrupa objetos iguales (19-24 m)"]'),
	(373, 111, 'ESCENA 2: LA CHACRA', '246', 'CuentameCuento', '["El niÃ±o escucha y relaciona el relato de la chacra de lo que realiza papÃ¡ y mamÃ¡."]'),
	(374, 112, 'AYUDO A COCINAR', '77', 'VidaFamilia', '[]'),
	(375, 112, 'PREPARAMOS  LA MESA PARA COMER', '207', 'JugandoAprendo', '["Relaciona la funciÃ³n de los objetos mientras se prepara la mesa para comer."]'),
	(376, 112, 'ROMPECABEZAS 8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(377, 112, 'LIBRO 8: A MARÃA LE GUSTA JUGAR', '264', 'CuentameCuento', '["El niÃ±o asocia las escenas con su vida cotidiana."]'),
	(378, 113, 'A GUARDAR A GUARDAR', '78', 'VidaFamilia', '[]'),
	(379, 113, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
	(380, 113, 'LOS PASAJEROS DE COLORES SE PASEAN', '209', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego.","Encaja varias piezas en un tablero, adecuando sus manos y dedos"]'),
	(381, 113, 'LIBRO 10 MARÃA PREGUNTA Â¿DÃ“NDE  ESTÃ?', '265', 'CuentameCuento', '["El niÃ±o escucha atentamente el cuento."]'),
	(382, 114, 'A GUARDAR', '78', 'VidaFamilia', '[]'),
	(383, 114, 'LA CASITA DE TAPAS', '201', 'JugandoAprendo', '["Realiza movimientos de mayor precisiÃ³n con sus manos para armar una casita  con tapas.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(384, 114, 'ROMPECABEZAS 8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(385, 114, 'LIBRO 7: MI DÃA', '262', 'CuentameCuento', '["El niÃ±o reconoce y asocia las rutinas del dÃ­a."]'),
	(386, 115, 'ACOMPAÃ‘A A MAMA EN LA CHACRA', '79', 'VidaFamilia', '[]'),
	(387, 115, 'SACO UNO, SACO TODOS', '210', 'JugandoAprendo', '["Diferencia entre lleno y vacÃ­o â€“ mucho â€“ y poco.","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m)"]'),
	(388, 115, 'LOTERÃA 3: 6 OBJETOS FAMILIARES', '208', 'CuentameCuento', '["Encaja objetos segÃºn la lÃ¡mina","Relaciona objetos segÃºn su funciÃ³n: peine para peinarse, taza para tomar, etc.","Agrupa objetos iguales (19-24 m)"]'),
	(389, 115, 'ESCENA 3: LA PLAZA PRINCIPAL / LA PESCA', '274', 'CuentameCuento', '["El niÃ±o escucha y relaciona el relato de la plaza principal."]'),
	(390, 116, 'ACOMPAÃ‘A A MAMA EN LA CHACRA.', '79', 'VidaFamilia', '[]'),
	(391, 116, 'JUEGO CON LOS BLOQUES  DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m).","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
	(392, 116, 'LOTERIA 4', '211', 'JugandoAprendo', '["Encaja objetos segÃºn la lÃ¡mina","Agrupa objetos iguales (19-24 m)"]'),
	(393, 116, 'ESCENA 4: LA FIESTA  PATRONAL', '211', 'CuentameCuento', '["El niÃ±o escucha y relaciona el relato de la fiesta patronal."]'),
	(394, 117, 'Â¡QUE LINDA LA NATURALEZA!', '80', 'VidaFamilia', '[]'),
	(395, 117, 'JUEGO A BAÃ‘AR A LA MUÃ‘ECA', '212', 'JugandoAprendo', '["Dramatiza situaciones conocidas de su vida diaria mientras baÃ±a a la muÃ±eca","Juega representando actividades de la vida cotidiana (da de comer a la muÃ±eca, baÃ±a a la muÃ±eca, imita el carro) utilizando diversos objetos para completar sus juegos de imitaciÃ³n (19-24 m)"]'),
	(396, 117, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(397, 117, 'LIBRO 10 MARÃA PREGUNTA Â¿DÃ“NDE  ESTÃ?', '265', 'CuentameCuento', '["El niÃ±o escucha atentamente."]'),
	(398, 118, 'QUE LINDA LA NATURALEZA', '80', 'VidaFamilia', '[]'),
	(399, 118, 'IMITO A MAMA', '213', 'JugandoAprendo', '["Imita las acciones que hace mama.","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m)"]'),
	(400, 118, 'ROMPECABEZAS', '214', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Describe escenas sencillas que observa en una lÃ¡mina"]'),
	(401, 118, 'SECUENCIA 1: CAMBIO DE ROPA', '249', 'CuentameCuento', '["MamÃ¡ describe al niÃ±o  los pasos de cambiarse de ropa."]'),
	(402, 119, ' â€œEL LÃDERâ€', '81', 'VidaFamilia', '[]'),
	(403, 119, 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
	(404, 119, 'LOTERÃA 5', '215', 'CuentameCuento', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
	(405, 119, 'SECUENCIA 2 EL CEPILLADO DE LOS DIENTES', '250', 'CuentameCuento', '["El niÃ±o observa los pasos de cepillado de dientes"]'),
	(406, 120, 'EL LÃDERâ€', '81', 'VidaFamilia', '[]'),
	(407, 120, 'MI CARRO SE PASEA', '216', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m)"]'),
	(408, 120, 'ROMPECABEZAS 10', '217', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Se expresa por medio de frases de dos o tres palabras"]'),
	(409, 120, 'SECUENCIA 4 SEMBRAMOS PARA COMER', '252', 'CuentameCuento', '["El niÃ±o observa y escucha  los pasos de sembrando."]'),
	(410, 121, 'Â¿POR DÃ“NDE NOS FUIMOS?', '82', 'VidaFamilia', '[]'),
	(411, 121, 'LOS ANIMALES ESTÃN  CERCA Y LEJOS  DE SU CASA', '218', 'JugandoAprendo', '["Corre en diferentes direcciones sin caerse ni chocarse.","Transforma los objetos con creatividad durante el juego: Utiliza una manta como capa, etc"]'),
	(412, 121, 'JUEGO CON LOS BLOQUES DE DIFERENTES  FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
	(413, 121, 'LIBRO 11:  MARÃA Y JUAN JUEGAN CON LOS COLORES', '266', 'CuentameCuento', '["El niÃ±o(a) conversa con mamÃ¡ y describe imÃ¡genes."]'),
	(414, 122, 'Â¿POR DÃ“NDE  NOS FUIMOS?', '82', 'VidaFamilia', '[]'),
	(415, 122, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
	(416, 122, 'EL COLECTIVO HACE LO QUE LE PEDIMOS', '219', 'JugandoAprendo', '["El niÃ±o hace correr o parar al carrito cuando mamÃ¡ le indica.","Comprende indicaciones sencillas realizando la acciÃ³n"]'),
	(417, 122, 'MIS CARROS  VAN POR EL CAMINO', '220', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Realiza movimientos de mayor precisiÃ³n con sus dedos. P.e. abotona, desabotona, abrocha, desabrocha, sube y baja cierres, rasga con los dedos, abolilla, insera objetos en ranuras","Construye diversas formas: con bloques, piezas de construcciÃ³n"]'),
	(418, 122, 'ESCENA 3:  LA PLAZA PRINCIPAL ', '247', 'CuentameCuento', '["La niÃ±a(o) observa imÃ¡genes y conversa con mamÃ¡."]'),
	(419, 123, 'MANO  SOBRE LA MANO', '83', 'VidaFamilia', '[]'),
	(420, 123, 'HAGO UN COLLAR CON TODAS LAS TAPAS', '221', 'JugandoAprendo', '["Ensarta cuentas en con orificios pequeÃ±os","Apila objetos uno encima de otros con mÃ¡s de tres elementos (13-18 m)"]'),
	(421, 123, 'LOTERÃA 5', '215', 'CuentameCuento', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
	(422, 123, 'LIBRO 9 JUAN PREGUNTA Â¿CÃ“MO ES?', '264', 'CuentameCuento', '["El niÃ±o describe imÃ¡genes  del cuento."]'),
	(423, 124, 'MANO SOBRE  LA MANO', '83', 'VidaFamilia', '[]'),
	(424, 124, 'MUEVO LA ALMOHADA', '222', 'JugandoAprendo', '["Mantiene por breves momentos el equilibrio parado en un pie","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m)."]'),
	(425, 124, 'ROMPECABEZAS 10', '217', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Se expresa por medio de frases de dos o tres palabras"]'),
	(426, 124, 'ESCENA 5: LA FIESTA PATRONAL', '248', 'CuentameCuento', '["El niÃ±o observa imÃ¡genes y conversa con mamÃ¡."]'),
	(427, 125, 'SEMILLAS DE COLORES', '84', 'VidaFamilia', '[]'),
	(428, 125, 'MIS PRIMEROS  DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(429, 125, 'ROMPECABEZAS 11', '223', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Se expresa por medio de frases de dos o tres palabras"]'),
	(430, 125, 'SECUENCIA 7: VAMOS A PASTOREAR', '255', 'CuentameCuento', '["El niÃ±o mira y describe la secuencia de  imÃ¡genes"]'),
	(431, 126, 'SEMILLAS DE COLORES', '84', 'VidaFamilia', '[]'),
	(432, 126, 'LOS ANIMALES ESTÃN CERCA Y LEJOS DE SU CASA', '218', 'JugandoAprendo', '["Corre en diferentes direcciones sin caerse ni chocarse.","Transforma los objetos con creatividad durante el juego: Utiliza una manta como capa, etc."]'),
	(433, 126, 'LOTERÃA 6', '224', 'JugandoAprendo', '["Utiliza cuantificadores como mucho-poco, uno-ninguno.","Agrupa objetos iguales (19-24 m)"]'),
	(434, 126, 'SECUENCIA 5:  COMPRAMOS PESCADO CON PAPÃ', '250', 'CuentameCuento', '["El niÃ±o conversa con mamÃ¡ y Describe  la secuencia. "]'),
	(435, 127, 'JUGAMOS CON LA PELOTA', '85', 'VidaFamilia', '[]'),
	(436, 127, 'ADIVINA QUE  ES', '225', 'JugandoAprendo', '["Reconoce un objeto a partir del olor, sabor, textura, sonido aÃºn sin verlo","Busca objetos conocidos aunque no los tenga a la vista (19-24m)"]'),
	(437, 127, 'DIBUJA CON MAMÃ', '197', 'CuentameCuento', '["Garabatea libremente con mayor control de su movimiento.","Nombra objetos familiares que observa en ilustraciones"]'),
	(438, 127, 'SECUENCIA 6: LAVAMOS LA ROPA', '266', 'CuentameCuento', '["El niÃ±o escucha con atenciÃ³n lo que le cuenta mamÃ¡."]'),
	(439, 128, 'JUGAMOS CON LA PELOTA', '85', 'VidaFamilia', '[]'),
	(440, 128, 'LA CASITA DE TAPAS', '201', 'JugandoAprendo', '["Coloca las tapas siguiendo la lÃ¡mina de la casita.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(441, 128, 'LOTERÃA 6:  MUCHOS POCOS', '224', 'JugandoAprendo', '["Utiliza cuantificadores como mucho-poco, uno-ninguno","Agrupa objetos iguales (19-24 m)"]'),
	(442, 128, 'SECUENCIA 3: TEJEMOS UNA CHOMPA', '251', 'CuentameCuento', '["MamÃ¡ describe lÃ¡mina  contando la historia de la chompa."]'),
	(443, 129, 'COMO LOS CONEJITOS', '86', 'VidaFamilia', '[]'),
	(444, 129, 'HAGO DISTINTOS COLLARES', '226', 'JugandoAprendo', '["Ensarta cuentas en con orificios pequeÃ±os","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m)"]'),
	(445, 129, 'LOTERÃA 7', '227', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
	(446, 129, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Expresa de manera comprensible sus vivencias"]'),
	(447, 129, 'SECUENCIA 7: VAMOS A PASTOREAR', '255', 'CuentameCuento', '["El niÃ±o mira y describe la secuencia de  imÃ¡genes"]'),
	(448, 130, 'COMO LOS CONEJITOS', '86', 'VidaFamilia', '[]'),
	(449, 130, 'EL CARRO  VA LEJOS POR EL CAMINO', '228', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Construye diversas formas: con bloques, piezas de construcciÃ³n"]'),
	(450, 130, 'JUEGO CON LOS  BLOQUES DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["El Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
	(451, 130, 'SECUENCIA 2: EL CEPILLADO DE LOS DIENTES', '250', 'CuentameCuento', '["MamÃ¡ conversa con el niÃ±o(a) acerca del aseo."]'),
	(452, 131, 'LAS CHAPADAS', '87', 'VidaFamilia', '[]'),
	(453, 131, 'Â¿CUÃNTOS PASAJEROS HAY EN EL COLECTIVO?', '229', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Dramatiza situaciones conocidas, que contienen pequeÃ±os argumentos"]'),
	(454, 131, 'ROMPECABEZAS 11', '223', 'CuentameCuento', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
	(455, 131, 'LIBRO 11: MARÃA Y JUAN JUEGAN CON COLORES', '266', 'CuentameCuento', '["El niÃ±o(a) conversa con mamÃ¡ y describe imÃ¡genes."]'),
	(456, 132, 'LAS CHAPADAS', '87', 'VidaFamilia', '[]'),
	(457, 132, 'COCINAMOS', '230', 'JugandoAprendo', '["Dramatiza situaciones conocidas de su vida dirÃ­a mientras juegan a la cocinita.","Juega representando actividades cotidianas de la vida diaria utilizando objetos diversos para completar sus juegos de imitaciÃ³n (19-24 m)","Imita acciones rutinarias que realiza el adulto como: barrer, planchar, cocinar, etc. (13-18 m)"]'),
	(458, 132, 'LOTERÃA  7', '227', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
	(459, 132, 'SECUENCIA 3: TEJEMOS UNA CHOMPA ', '251', 'CuentameCuento', '["MamÃ¡ describe lÃ¡mina  contando la historia de la chompa."]'),
	(460, 133, 'TOCO, TOCO  LO QUE NOMBRO', '88', 'VidaFamilia', '[]'),
	(461, 133, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(462, 133, 'Â¿QUÃ‰ SERÃ?', '231', 'JugandoAprendo', '["Reconoce un objeto a partir del olor, sabor, textura, sonido aÃºn sin verlo","Busca objetos conocidos aunque no los tenga a la vista (19-24m)"]'),
	(463, 133, 'LIBRO 10: MARÃA PREGUNTA Â¿DÃ“NDE ESTÃ?', '265', 'CuentameCuento', '["El niÃ±o(a) Conversa con su mamÃ¡"]'),
	(464, 134, 'TOCA, TOCA LO QUE NOMBRO', '88', 'VidaFamilia', '[]'),
	(465, 134, 'Â¿CÃ“MO SE SIENTE Ã‰L BEBE?', '232', 'JugandoAprendo', '["Expresa de manera comprensible sus vivencias diarias.","Dramatiza situaciones conocidas, que contienen pequeÃ±os argumentos"]'),
	(466, 134, 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Nombra objetos familiares que observa en ilustraciones"]'),
	(467, 134, 'LIBRO 11: MARÃA Y JUAN JUEGAN CON COLORES', '266', 'CuentameCuento', '["El niÃ±o(a) conversa con mamÃ¡ y describe imÃ¡genes."]'),
	(468, 135, 'VEO, VEO Â¿QUÃ‰ VEZ?', '89', 'VidaFamilia', '[]'),
	(469, 135, 'EL GUSANO DE TAPITAS', '233', 'JugandoAprendo', '["Realiza movimientos de mayor precisiÃ³n con sus dedos.","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m) un poco forzada Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m) "]'),
	(470, 135, 'SECUENCIA 4:  SEMBRAMOS PARA COMER', '252', 'CuentameCuento', '["El niÃ±o mira la lÃ¡mina y relaciona con el trabajo de papÃ¡."]'),
	(471, 136, 'VEO, VEO Â¿QUÃ‰ VEZ?', '89', 'VidaFamilia', '[]'),
	(472, 136, 'ROMPECABEZAS12: LA NIÃ‘A', '234', 'JugandoAprendo', '["Expresa de manera comprensible sus vivencias diarias","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m) un poco forzada"]'),
	(473, 136, 'LOTERÃA 7 LAS ACCIONES DEL PERRO', '227', 'JugandoAprendo', '["El niÃ±o observa las acciones del perro y empareja con las cartillas."]'),
	(474, 136, 'SECUENCIA 5 COMPRAMOS PESCADO CON PAPÃ', '253', 'CuentameCuento', '["El niÃ±o conversa con mamÃ¡ y Describe  la secuencia. "]'),
	(475, 137, 'ENSALADA DE FRUTAS', '90', 'VidaFamilia', '[]'),
	(476, 137, 'LOS  ANIMALES  EN EL CAMPO', '235', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
	(477, 137, 'SECUENCIA 6: LAVAMOS LA ROPA', '254', 'CuentameCuento', '["El niÃ±o escucha con atenciÃ³n lo que le cuenta mamÃ¡."]'),
	(478, 138, 'ENSALADA DE  FRUTAS', '90', 'VidaFamilia', '[]'),
	(479, 138, 'LOTERÃA 8', '236', 'JugandoAprendo', '["Repite juego de palabras, rimas, canciones sencillas","Imita sonidos onomatopÃ©yicos (de animales y objetos que conoce)(13-18 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
	(480, 138, 'SECUENCIA 4: SEMBRAMOS PARA COMER', '252', 'CuentameCuento', '["MamÃ¡ conversa con el niÃ±o(a) acerca  de los alimentos que siembra y cosecha."]'),
	(481, 139, 'AYER HOY', '91', 'VidaFamilia', '[]'),
	(482, 139, 'LE DOY DE COMER A LA MUÃ‘ECA', '237', 'JugandoAprendo', '["Dramatiza situaciones conocidas, que contienen pequeÃ±os argumentos","Se expresa por medio de frases de dos o tres palabras (19-24 m)"]'),
	(483, 139, 'ROMPECABEZAS 12', '234', 'JugandoAprendo', '["Expresa de manera comprensible sus vivencias o comprende indicaciones sencillas"]'),
	(484, 139, 'LIBRO 8: A MARÃA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niÃ±o observa las imÃ¡genes y conversa con mamÃ¡."]'),
	(485, 140, 'AYER , HOY', '91', 'VidaFamilia', '[]'),
	(486, 140, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(487, 140, 'LOTERÃA 8', '236', 'JugandoAprendo', '["Nombra objetos familiares que observa en ilustraciones","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(488, 140, 'LIBRO 7: MI DÃA', '262', 'CuentameCuento', '["El niÃ±o conversa con mamÃ¡  acerca del cuento"]'),
	(489, 141, 'AYUDO  A SERVIR LA MESA', '92', 'VidaFamilia', '[]'),
	(490, 141, 'LOS  ANIMALES  EN EL CAMPO', '235', 'JugandoAprendo', '["Imita el sonido de los animales","Imita sonidos onomatopÃ©yicos (de animales y objetos que conoce)(13-18 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)","En sus conversaciones se puede distinguir 10 palabras como mÃ­nimo (19-24 m)"]'),
	(491, 141, 'LOTERÃA  8', '236', 'JugandoAprendo', '["Nombra objetos familiares que observa en ilustraciones","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
	(492, 141, 'LIBRO 9: JUAN PREGUNTA Â¿CÃ“MO ES?', '264', 'CuentameCuento', '["El niÃ±o conversa con mamÃ¡ y disfruta del cuento."]'),
	(493, 142, 'AYUDO A SERVIR LA MESA', '92', 'VidaFamilia', '[]'),
	(494, 142, 'JUEGO A LA MAMÃ  Y  EL PAPÃ', '238', 'JugandoAprendo', '["Dramatiza situaciones conocidas, que contienen pequeÃ±os argumentos","Juega representando actividades de la vida cotidiana (da de comer a la muÃ±eca, maneja el carro) utilizando objetos diversos para completar sus juegos de imitaciÃ³n (19-24 m)","Imita acciones rutinarias que realiza el adulto (13-18 m)"]'),
	(495, 142, 'LOTERÃA  9: CANTIDAD', '239', 'JugandoAprendo', '["Utiliza cuantificadores como mucho-poco, uno-ninguno","Agrupa objetos iguales (19-24 m)"]'),
	(496, 142, 'LIBRO 10: MARÃA PREGUNTA Â¿DÃ“NDE ESTÃ?', '265', 'CuentameCuento', '["El niÃ±o conversa con mamÃ¡ y disfruta del cuento."]'),
	(497, 143, 'UN ALMUERZO PARA MIS INVITADOS', '93', 'VidaFamilia', '[]'),
	(498, 143, 'EL GUSANITO  DE TAPITAS', '233', 'JugandoAprendo', '["Realiza movimientos de mayor precisiÃ³n con sus dedos.","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m) un poco forzada","Agrupa objetos iguales (19-24 m)"]'),
	(499, 143, 'ROMPECABEZAS 12', '234', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Comprende indicaciones sencillas realizando la acciÃ³n (13-18 m) un poco forzada"]'),
	(500, 143, 'ADIVINO Y EMPAREJO', '240', 'JugandoAprendo', '["Reconoce un objeto a partir del olor, sabor, textura, sonido, aÃºn sin verlo","Busca objetos conocidos aunque no los tenga a la vista (19-24"]'),
	(501, 143, 'LIBRO 11: MARÃA Y JUAN JUEGAN CON COLORES', '266', 'CuentameCuento', '["El niÃ±o conversa con mamÃ¡ y disfruta del cuento."]'),
	(502, 144, 'UN ALMUERZO PARA MIS INVITADOS', '93', 'VidaFamilia', '[]'),
	(503, 144, 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Nombra objetos familiares que observa en ilustraciones"]'),
	(504, 144, 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
	(505, 144, 'SECUENCIA 7: VAMOS A PASTOREAR', '255', 'CuentameCuento', '["El niÃ±o conversa con mamÃ¡ y disfruta del cuento."]');
/*!40000 ALTER TABLE `fichas` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
