INSERT INTO `latigazo`.`fichas` (`semana`, `titulo`, `numero`, `tipo`, `descripcion`) VALUES 
('1', 'OBSERVO A MI BEBE', '1', 'VidaFamilia', '[]'),
('2', '¿CÓMO CALMO A MI BEBE?', '2', 'VidaFamilia', '[]'),
('3', '¿COMO ES MI BEBE?', '3', 'VidaFamilia', '[]'),
('4', 'CONVERSO CON MI BEBE', '4', 'VidaFamilia', '[]'),
('5', 'ME GUSTA  QUE MAMA ME ABRACE', '5', 'VidaFamilia', '[]'),
('5', 'JUEGA CON TU BEBE DEMOSTRÁNDOLE TU AMOR Y CARIÑO', '94', 'JugandoAprendo', '["Mamá juega con su bebe demostrándole amor : cargándolo, arrullándolo, meciéndolo despacio demostrando alegría y entusiasmo"]'),
('6', 'ME GUSTA  CUANDO CANTAS', '6', 'VidaFamilia', '[]'),
('6', '¿COMO TE PERCIBE TU BEBÉ?', '95', 'JugandoAprendo', '["Mamá atiende tranquila a su bebe y lo hace sentir bien."]'),
('7', 'EL SUEÑO DE TU BEBE', '8', 'VidaFamilia', '[]'),
('7', 'MI  BEBE ME ESCUCHA SIEMPRE', '96', 'JugandoAprendo', '["El bebé se siente feliz cuando escucha a mamá."]'),
('8', 'ME GUSTA TU DELICADEZA', '7', 'VidaFamilia', '[]'),
('8', 'JUEGA CON TU BEBE DEMOSTRÁNDOLE TU AMOR Y CARIÑO', '94', 'VidaFamilia', '[]'),
('8', 'JUEGA CON TU BEBE DEMOSTRÁNDOLE TU AMOR Y CARIÑO', '94', 'JugandoAprendo', '["El bebé se siente feliz cuando escucha a mamá."]'),
('9', 'IMITAR LOS SONIDOS QUE HACE MI BEBE', '10', 'VidaFamilia', '[]'),
('9', 'JUGANDO CON MÍ BEBE.', '97', 'JugandoAprendo', '["El niño/a fija su mirada con muchos interés en los objetos que están cerca de él.","Observa con interés las actividades que realizan las personas a su alrededor","Explora el ambiente en confianza según sus posibilidades"]'),
('9', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('10', 'IMITAR LOS SONIDOS QUE HACE ÉL BEBE', '10', 'VidaFamilia', '[]'),
('10', 'MIS OJITOS', '98', 'JugandoAprendo', '["Sigue con la mirada a su cuidador o lo objetos que se le muestra.","Expresa sus emociones, deseos y/o necesidades utilizando variados movimientos corporales y gestuales (agita brazos, estira piernas, mueve cabeza, frunce el ceño)"]'),
('10', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('11', '¡BUUU!', '11', 'VidaFamilia', '[]'),
('11', 'MANITO  MANITO', '99', 'JugandoAprendo', '["Reconoce los gestos, la voz de su cuidador y sonidos familiares, respondiendo con la mirada, mímica o movimientos.","Mueve libremente y con energía brazos y piernas (p.e. juega activamente con manos y pies)"]'),
('11', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('12', '¡BUUU!', '11', 'VidaFamilia', '[]'),
('12', 'SUENA LA SONAJA', '100', 'JugandoAprendo', '["El niño/a busca la sonaja con la mira o movimientos, sonidos o gestos frente al sonido de la misma.","Mueve libremente y con energía brazos y piernas (p.e. juega activamente con manos y pies)","Coge objetos pequeños (que entran en su mano) utilizando la presión palmar"]'),
('12', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('13', 'CARAS GRACIOSAS', '12', 'VidaFamilia', '[]'),
('13', 'QUIERO TOCAR LO QUE VEO', '101', 'JugandoAprendo', '["El niño/a Intenta alcanzar objetos con su mano, aunque aún no pueda sujetarlos.","Estira sus brazos para alcanzar objetos que llamen su atención"]'),
('13', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('14', 'CARAS GRACIOSAS', '12', 'VidaFamilia', '[]'),
('14', 'OBSERVO  MI ENTORNO', '102', 'JugandoAprendo', '["El niño/a gira la cabeza o cuerpo  para seguir le movimiento del juguete que la mama le presenta","Observa con interés las actividades que realizan las personas a su alrededor.","Expresa sus emociones, deseos y/o necesidades utilizando variados movimientos corporales y gestuales (agita brazos, estira piernas, mueve cabeza, frunce el ceño)"]'),
('14', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('15', 'DESCUBRO MI CUERPO', '13', 'VidaFamilia', '[]'),
('15', 'AGARRAR Y SOLTAR', '103', 'JugandoAprendo', '["El niño/a  sostiene la sonaja por un momento breve.","El bebe sostiene y mueve la sonaja por unos segundos.","Manipula objetos que tiene en sus manos vivenciando espontáneamente las características de los objetos: forma, peso, textura, temperatura."]'),
('15', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('16', 'DESCUBRO MI CUERPO', '13', 'VidaFamilia', '[]'),
('16', 'EXPLORAR LA SONAJA', '104', 'JugandoAprendo', '["El niño/a coge la sonaja y se lo lleva a la boca para chuparla o morderla","El niño/a sostiene y mueve la sonaja por unos segundos.","Coge objetos pequeños (que entran en su mano) utilizando la prensión palmar.","Manipula objetos que tiene en sus manos vivenciando espontáneamente las características de los objetos: forma, peso, textura, temperatura"]'),
('16', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('17', 'MIS PRIMEROS DESCUBRIMIENTOS', '14', 'VidaFamilia', '[]'),
('17', 'ALCANZAR LA SONAJA QUE ESTÁ LEJOS', '105', 'JugandoAprendo', '["Intenta alcanzar objetos con su mano, cuando su mama se lo muestra.","Estira sus brazos para alcanzar objetos que llamen su atención","Coge objetos pequeños (que entran en su mano) utilizlando la prensión palmar","Coge objetos que están a su alcance con ambas manos y se lo lleva a la boca."]'),
('17', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('18', 'MIS PRIMEROS DESCUBRIMIENTOS', '14', 'VidaFamilia', '[]'),
('18', 'DESCUBRO EL ARO DE JEBE', '106', 'JugandoAprendo', '["El niño/a coge el aro y se lo lleva a la boca para chuparlo o morderlo.","Estira sus brazos para alcanzar objetos que llamen su atención","Coge objetos pequeños (que entran en su mano) utilizando la prensión palmar.","Intenta alcanzar objetos con su mano, aunque aún se le escapen"]'),
('18', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('19', 'METO  MIS MANOS Y MIS PIES', '15', 'VidaFamilia', '[]'),
('19', 'HAGO SONAR LA SONAJA', '107', 'JugandoAprendo', '["El niño/a  coge la sonaja y la mueve para que suene.","Estira sus brazos para alcanzar objetos que llamen su atención","Coge objetos que están a su alcance con ambas manos y se lo lleva a la boca","Manipula objetos que tiene en sus manos vivenciando espontáneamente las características de los objetos: forma, peso, textura, temperatura."]'),
('19', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('20', 'METO  MIS MANOS Y MIS PIES', '15', 'VidaFamilia', '[]'),
('20', 'HAGO SONAR LA SONAJA', '107', 'JugandoAprendo', '["Produce con los objetos diversos sonidos que le son agradables","Estira sus brazos para alcanzar objetos que llamen su atención.","Coge objetos que están a su alcance con ambas manos y se lo lleva a la boca"]'),
('20', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('21', 'COSQUILLITAS Y PATADITAS', '16', 'VidaFamilia', '[]'),
('21', 'DISFRUTAMOS DE LA MÚSICA  JUNTOS', '108', 'JugandoAprendo', '["El niño/a se divierte en los brazos de mama al ritmo de la música que ella le canta.","Reconoce a la persona que lo cuida.","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él)"]'),
('21', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('22', 'COSQUILLITAS Y PATADITAS', '16', 'VidaFamilia', '[]'),
('22', 'MIRA COMO RUEDA', '109', 'JugandoAprendo', '["El niño/a observa la botella que su cuidador hacer rodar delante de él.","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)."]'),
('22', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('23', 'SIENTO  EL AGUA Y EL JABÓN', '17', 'VidaFamilia', '[]'),
('23', '¡ENCUÉNTRAME¡', '110', 'JugandoAprendo', '["El niño/a se divierte y expresa emociones cuando la mama se tapa o destapa la cara.","Reconoce a la persona que lo cuida.","Pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura"]'),
('23', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('24', 'SIENTO  EL AGUA Y EL JABÓN', '17', 'VidaFamilia', '[]'),
('24', 'AGITO LAS MARACAS', '111', 'JugandoAprendo', '["El niño/a coge y explora las marcas, las hace sonar o se las lleva a la boca.","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)"]'),
('24', 'SALUDO AL BEBE', '112', 'JugandoAprendo', '["El niño/a observa con atención el juego que el cuidador hace con los títeres","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.).","Pasa un objeto de una mano a otra.","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él)"]'),
('24', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('25', 'MMMM, ¿QUÉ ES?', '18', 'VidaFamilia', '[]'),
('25', 'GOLPEO EL ARO', '113', 'JugandoAprendo', '["El niño/a observa cómo se mueve el aro e intenta o lo alcanza a golpear  con la mano.","Observa con interés las acciones que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Pasa un objeto de una mano a otra"]'),
('25', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('26', 'MMMM, ¿QUÉ ES?', '18', 'VidaFamilia', '[]'),
('26', 'TE VEO  Y NO TE VEO', '114', 'JugandoAprendo', '["El niño/a se divierte y juega con su mama a taparse la cara con el pañuelo","Reconoce a la persona que lo cuida.","Se pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
('26', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('27', 'ME GUSTAN TUS CARICIAS TU VOZ', '19', 'VidaFamilia', '[]'),
('27', 'AGITAR LA SONAJA CON FUERZA', '115', 'JugandoAprendo', '["El niño/a hace sonar la sonaja moviéndola en diferentes direcciones","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
('27', 'SACO LOS CUBOS DEL RECIPIENTE', '116', 'JugandoAprendo', '["El niño/a Introduce y saca objetos pequeños de un recipiente (con todos los dedos)","Pasa un objeto de una mano a otra.","Recoge objetos pequeños arrastrando los dedos (movimientos rastrillo).","Realiza diversas acciones con y entre los objetos:  los golpea entre sí, los frota, los saca y los mete de un recipiente, etc."]'),
('27', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('28', 'ME GUSTAN TUS CARICIAS TU VOZ', '19', 'VidaFamilia', '[]'),
('28', 'SACO LOS CUBOS DE RECIPIENTE', '116', 'JugandoAprendo', '["Introduce y saca objetos pequeños de un recipiente (con todos los dedos)","Pasa un objeto de una mano a otra.","Recoge objetos pequeños arrastrando los dedos (movimientos rastrillo).","Realiza diversas acciones con y entre los objetos:  los golpea entre sí, los frota, los saca y los mete de un recipiente, etc."]'),
('28', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('29', 'SE QUIÉNES SON', '20', 'VidaFamilia', '[]'),
('29', 'ATRAPO EL ARO', '117', 'JugandoAprendo', '["El niño/a Se desplaza intentado coger el aro","Observa la trayectoria de los objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Observa con interés las actividades que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)"]'),
('29', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('30', 'SE QUIÉNES SON', '20', 'VidaFamilia', '[]'),
('30', 'JUGANDO CON LA PELOTA DE TRAPO', '118', 'JugandoAprendo', '["El niño/a de desplaza  intentado coger la pelota","Observa la trayectoria de los objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
('30', '¿A DÓNDE SE FUE MI JUGUETE?', '119', 'JugandoAprendo', '["El niño/a se encuentra el juguete que está escondido debajo del pañuelo","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
('30', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('31', 'CUÉNTAME HISTORIAS', '21', 'VidaFamilia', '[]'),
('31', 'VOLTEO EL RECIPIENTE CON LOS CUBOS', '120', 'JugandoAprendo', '["El niño/a voltea el recipiente para que caigan los cubos.","Pasa un objeto de una mano a otra.","Observa la trayectoria de los objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura."]'),
('31', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('32', 'NUESTRAS CANCIONES', '22', 'VidaFamilia', '[]'),
('32', 'GOLPEO LAS MARACAS COMO TAMBOR', '121', 'JugandoAprendo', '["El niño/a golpea las maracas contra un recipiente como si fuera tambor y se divierte con los sonidos que hace.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Pasa un objeto de una mano a otra.","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él).","Reacciona a través del movimiento y/o emitiendo sonidos al reconocer melodías conocidas (balancea su cuerpo, moviendo la cabeza)"]'),
('32', 'CANCIÓN', '0', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('33', 'SUCIO O LIMPIO', '23', 'VidaFamilia', '[]'),
('33', 'ATRAPO LA PELOTA', '122', 'JugandoAprendo', '["El niño/a  atrapa o intenta atrapar la pelota.","Observa la trayectoria de objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad."]'),
('33', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El bebé disfruta la canción."]'),
('34', 'SUCIO O LIMPIO', '23', 'VidaFamilia', '[]'),
('34', 'RUEDO LA BOTELLA HACIA TI', '123', 'JugandoAprendo', '["El niño/a observa con atención e intenta coger la botella mientras rueda.","Pasa un objeto de una mano a otra.","Observa la trayectoria de objetos que lanza o deja caer experimentando (de manera intuitiva) la noción de profundidad.","Realiza diversas acciones con y entre los objetos: los golpea entre sí, los frota, los saca y los mete de un recipiente, etc.","Explora el ambiente con confianza, según sus posibilidades"]'),
('34', 'CANCIÓN', '0', 'CuentameCuento', '["El niño/a  disfruta de la canción y trata de imitar algunos sonidos."]'),
('35', 'QUIERO TOCAR  LO QUE COMO', '24', 'VidaFamilia', '[]'),
('35', 'SACO AFUERA LOS BLOQUES', '124', 'JugandoAprendo', '["El niño/a saca los cubos del recipiente.","Recoge objetos pequeños arrastrando los dedos (movimientos de rastrillo).","Pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Realiza diversas acciones con y entre los objetos: los golpea entre sí, los frota, los saca y los mete de un recipiente, etc"]'),
('35', 'EL COLLAR DE AROS', '125', 'JugandoAprendo', '["El niño/a Explora los objetos con manos y/o boca.","Observa con interés las actividades que realizan las personas a su alrededor (niños jugando, personas conversando, etc.)","Pasa un objeto de una mano a otra."]'),
('35', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño señala imágenes que ve."]'),
('36', 'QUIERO TOCAR  LO QUE COMO', '24', 'VidaFamilia', '[]'),
('36', 'APAREZCO Y DESAPAREZCO', '126', 'JugandoAprendo', '["Observa con atención a mamá, mientras esta hace aparecer y desaparecer al juguete.","Pasa un objeto de una mano a otra.","Explora los objetos con manos y/o boca descubriendo las características de los objetos por intuición:  textura, peso, forma, temperatura."]'),
('36', 'CANCIÓN', '0', 'CuentameCuento', '["El niño señala imágenes que ve."]'),
('37', 'EXPLORO LOS OBJETOS DEL HOGAR', '25', 'VidaFamilia', '[]'),
('37', 'JALO EL ARO', '127', 'JugandoAprendo', '["El niño/a jala el aro para acercarlo a él.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se meta en cajas, acomodando su cuerpo de acuerdo a sus posibilidades."]'),
('37', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
('38', 'EXPLORO LOS OBJETOS DEL HOGAR', '25', 'VidaFamilia', '[]'),
('38', 'EXPLORO DOS TEXTURAS DIFERENTES', '129', 'JugandoAprendo', '["El niño/a se mantiene sentado sin ayuda mientras juega con las pelotas.","Pasa un objeto de una mano a otra (6-9m).","Realiza diversas acciones con y entre los objetos: los golpea entre sí, los frota, los saca y los mete de un recipiente, etc. (6-9m).","Ubica fácilmente la procedencia de un sonido (voltea la cabeza, se desplaza hacia él) (6-9m).","Imita la entonación del adulto al escuchar conversaciones (6-9m)"]'),
('38', 'GATEO POR EL TÚNEL', '128', 'JugandoAprendo', '["Se desplaza gateando por el túnel.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Explora el ambiente con confianza, según sus posibilidades.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se meta en cajas, acomodando su cuerpo de acuerdo a sus posibilidades."]'),
('38', 'CANCIÓN', '0', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
('39', 'ACCIONES DE CORTESÍA', '26', 'VidaFamilia', '[]'),
('39', 'GOLPEO LOS CUBOS', '131', 'JugandoAprendo', '["El niño/a golpe el cubo disfrutando de los sonidos que hace.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Escucha diversos sonidos e intenta imitarlos vocalizando con claridad dos sílabas (\"dada\", \"papa\", etc.).","Se mantiene sentado y sin ayuda mientras juega","Utiliza \"sus\" palabras otorgándoles significado."]'),
('39', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño conoce y señala imágenes que ve."]'),
('40', 'ACCIONES DE CORTESÍA', '26', 'VidaFamilia', '[]'),
('40', 'ATRAPO LA BOTELLA', '126', 'JugandoAprendo', '["El niño/a se dirige a alcanzar la botella mientras mama la va empujando.","Explora el ambiente con confianza, según sus posibilidades.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc.","Se desplaza gateando."]'),
('40', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño conoce y señala imágenes que ve."]'),
('41', 'NUESTRAS CANCIONES', '22', 'VidaFamilia', '[]'),
('41', 'EL ARO SUBE Y BAJA', '132', 'JugandoAprendo', '["El niño/a Juega con el aro, subiéndolo y bajándolo.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura"]'),
('41', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
('42', 'NUESTRAS CANCIONES', '22', 'VidaFamilia', '[]'),
('42', 'ENCUENTRO EL JUGUETE QUE NO VEO', '133', 'JugandoAprendo', '["El niño/a Encuentra el juguete escondido debajo del pañuelo","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc.","Se mantiene sentado y sin ayuda mientras juega."]'),
('42', 'EL COLLAR Y EL RECIPIENTE', '134', 'JugandoAprendo', '["Introduce y saca el collar de un recipiente utilizando los dedos índice y pulgar.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se mantiene sentado y sin ayuda mientras juega.","Manipula diversos recipientes interesándose en el interior de estos (noción de contenido) a partir de su propio cuerpo y diversos objetos: introduce su cabeza en una caja para observar su contenido, se mete dentro de una canasta, etc."]'),
('42', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["El niño  conoce y señala imágenes que ve."]'),
('43', 'ME DIVIERTO CON LA MÚSICA', '27', 'VidaFamilia', '[]'),
('43', 'RUEDO EL TARRO', '135', 'JugandoAprendo', '["El niño/a rueda el tarro para que haga sonido y disfruta del mismo.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se para con apoyo.","Da algunos pasos hacia adelante con apoyo.","Escucha diversos sonidos e intenta imitarlos vocalizando con claridad dos sílabas (\"dada\", \"papa\", etc.)."]'),
('43', 'LIBRO DE TELA', '-1', 'CuentameCuento', '["Disfruta de canciones que mama le canta"]'),
('44', 'ME DIVIERTO CON LA MÚSICA', '27', 'VidaFamilia', '[]'),
('44', 'GATEO POR EL TÚNEL', '128', 'JugandoAprendo', '["Se desplaza gateando por el túnel.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Explora el ambiente con confianza según sus posibilidades.","Explora los objetos con las manos y/o boca descubriendo las características de los objetos por intuición: textura, peso, forma, temperatura.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se mete en cajas acomodando su cuerpo de acuerdo a sus posibilidades."]'),
('44', 'CANCIÓN', '0', 'CuentameCuento', '["El niño/a baila al compás de la música que mama le canta."]'),
('45', '¿DÓNDE ESTÁ MÍ…?', '28', 'VidaFamilia', '[]'),
('45', 'GATEO POR EL TÚNEL', '128', 'JugandoAprendo', '["El niño/a  Se desplaza gateando por el túnel.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Explora el ambiente con confianza, según sus posibilidades."]'),
('45', 'LOS OBJETOS- Libro 1', '256', 'CuentameCuento', '["El niño/a observa con atención y señala objetos."]'),
('46', 'DÉJAME INTENTARLO', '29', 'VidaFamilia', '[]'),
('46', 'ENCESTO LAS PELOTAS', '136', 'JugandoAprendo', '["Lanza objetos a distancia corta.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc","Hace rodar una pelota con ambas mano.","Se ubica en el espacio y establece relaciones entre su cuerpo y los objetos: se dirige a alcanzar lo que desea, se mete en cajas acomodando su cuerpo de acuerdo a sus posibilidades"]'),
('46', '6 OBJETOS', '241', 'CuentameCuento', '[" El niño observa y nombra algunos objetos."]'),
('47', 'MI PLATO LLENO  Y DESPUÉS VACÍO', '30', 'VidaFamilia', '[]'),
('47', 'ENCUENTRO EL JUGUETE QUE NO VEO', '133', 'JugandoAprendo', '["Observa un objeto que se oculta debajo del pañuelo.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se mantiene sentado y sin ayuda mientras juega.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc."]'),
('47', 'MIS EMOCIONES – Libro 2', '257', 'CuentameCuento', '["El niño describe imágenes del cuento."]'),
('48', 'CUENTOS', '31', 'VidaFamilia', '[]'),
('48', 'JUEGO CON 6  CUBOS', '138', 'JugandoAprendo', '["El niño/a levanta el recipiente para encontrar el cubo que esta debajo del mismo.","Reconoce personas u objetos familiares buscándolas con la mirada cuando se las nombran.","Se mantiene sentado y sin ayuda mientras juega.","Manipula un objeto para producir un resultado esperado para él, presiona una tecla, empuja una pelota para que ruede, suelta un objeto para escuchar el sonido, jala un mantel para alcanzar un objeto, golpea la torre con su mano para que caiga, etc.","Señala un objeto conocido cuando se lo nombra."]'),
('48', 'LAMINA 2: 9 OBJETOS - ', '242', 'CuentameCuento', '[" El  niño mira y conoce objetos."]'),
('49', 'CONTAR HISTORIAS INVENTADAS', '32', 'VidaFamilia', '[]'),
('49', 'COLOCO OBJETOS DENTRO DE LA BOTELLA', '139', 'JugandoAprendo', '["El niño coloca con precisión objetos dentro de la botella.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Imita acciones rutinarias que realiza el adulto (barrer, lavar, planchar, etc.)","Colabora colocando los objetos en su lugar cuanto se lo piden."]'),
('49', 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El  niño mira y conoce objetos."]'),
('50', 'CADA COSA EN SU LUGAR', '33', 'VidaFamilia', '[]'),
('50', 'EMPUJO  EL JUGUETE', '140', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
('50', 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce sus emociones."]'),
('51', 'LA BASURA TAMBIÉN TIENE SU LUGAR', '34', 'VidaFamilia', '[]'),
('51', 'ENCESTO LAS PELOTAS', '133', 'JugandoAprendo', '["Lanza la pelota hacia el recipiente desde una distancia corta.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
('51', 'EL TITERE APARECE Y DESAPARECE', '141', 'JugandoAprendo', '["El Niño/a busca el juguete escondido.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple."]'),
('51', 'LAMINA 1:6 OBJETOS', '241', 'CuentameCuento', '["El  niño mira y conoce objetos."]'),
('52', 'CUENTOS', '35', 'VidaFamilia', '[]'),
('52', 'JUEGO CON 4 CUBOS', '138', 'JugandoAprendo', '["Encuentra los cubos ocultos","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple"]'),
('52', 'LAMINA 2: 9 OBJETOS', '242', 'CuentameCuento', '["El niño conoce objetos  y para qué sirven"]'),
('53', 'DE LAS ACCIONES A LAS PALABRAS', '36', 'VidaFamilia', '[]'),
('53', 'ENCUENTRO  MI JUGUETE DEBAJO DEL PAÑUELO CORRECTO', '143', 'JugandoAprendo', '["Busca objetos totalmente ocultos","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('53', 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El niño conoce objetos  y para qué sirven."]'),
('54', ' “HACER COMO SI …”', '37', 'VidaFamilia', '[]'),
('54', 'ME ESCONDO', '258', 'JugandoAprendo', '["Se desplaza por el espacio y reconoce cuando está dentro o afuera.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('54', 'LIBRO 3:  LOS ANIMALES', '-2', 'CuentameCuento', '["El niño reconoce y nombra los animales que observa."]'),
('55', 'BAILAMOS', '38', 'VidaFamilia', '[]'),
('55', 'RUEDO EL TARRO DISTINTOS SUPERFICIES', '145', 'JugandoAprendo', '["Rueda el tarro en diferentes superficies siguiendo indicaciones de mamá.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('55', 'LAMINA 1:6 OBJETOS', '241', 'CuentameCuento', '["El niño reconoce y nombra objetos."]'),
('56', 'LOS ALIMENTOS', '39', 'VidaFamilia', '[]'),
('56', 'ME ESCONDO', '144', 'JugandoAprendo', '["Se desplaza por el espacio y reconoce cuando está dentro o afuera","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\""]'),
('56', 'HAGO TORRES DE 6 CUBOS', '146', 'JugandoAprendo', '["Coloca los cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('56', 'LAMINA 2 : NUEVE  OBJETOS', '242', 'CuentameCuento', '["El niño reconoce y nombra objetos, identificando para qué sirven."]'),
('57', '¿QUÉ HACEN LAS PERSONAS?', '40', 'VidaFamilia', '[]'),
('57', 'SONIDO… SILENCIO', '147', 'JugandoAprendo', '["El niño controla el movimiento de las maracas identificando el sonido y silencio.","Comprende el sentido del NO (p.e. detiene una acción cuando se le dice NO)."]'),
('57', 'HAGO TORRES CON SEIS CUBOS', '146', 'JugandoAprendo', '["Coloca los cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\".","Utiliza palabras o fragmentos de palabra para designar personas u objetos conocidos: \"Tata\" para indicar abuelo, \"pan\" cuando quiere pan, etc.","Señala un objeto conocido cuando se lo nombra (10-12 m)","Utiliza \"sus\" palabras otorgándoles significado  (10-12 m)."]'),
('57', 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El niño reconoce y nombra  objetos."]'),
('58', 'NUESTRAS DANZAS', '41', 'VidaFamilia', '[]'),
('58', 'ENCAJO EL VASO PEQUEÑO DENTRO DEL MAS GRANDE', '148', 'JugandoAprendo', '["Encaja el vaso pequeño dentro del vaso grande.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Intenta hacer cosas por sí mismo (ej. Intenta guardar los juguetes, abrocharse el abrigo aunque no lo logre, quitarse la ropa, abrir el lavamanos, manejar la cuchara, beber de una taza, etc.).","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
('58', 'EMPUJO EL JUGUETE', '140', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Utiliza palabras o fragmentos de palabra para designar personas u objetos conocidos: \"Tata\" para indicar abuelo, \"pan\" cuando quiere pan, etc.","Señala un objeto conocido cuando se lo nombra (10-12 m).","Utiliza \"sus\" palabras otorgándoles significado  (10-12 m)."]'),
('58', 'LAMINA 2 : NUEVE  OBJETOS', '242', 'CuentameCuento', '["El niño aprende el nombre de los objetos y para qué sirven."]'),
('59', 'CARITA REDONDA', '42', 'VidaFamilia', '[]'),
('59', 'LLENAMOS TODAS LAS BOTELLAS', '149', 'JugandoAprendo', '["Llena la botella con mucha precisión haciendo uso de objetos de diferente tamaño.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple"]'),
('59', 'LAMINA  3:DOCE  OBJETOS', '243', 'CuentameCuento', '["El niño reconoce animales y objetos  de su entorno."]'),
('60', 'ESPEJITO ESPEJITO', '43', 'VidaFamilia', '[]'),
('60', 'ROMPECABEZAS 1', '150', 'JugandoAprendo', '["Encaja las piezas del rompe cabezas.","-Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
('60', 'LIBRO 3 : LOS ANIMALES', '258', 'CuentameCuento', '["El niño escucha y reconoce sonidos de los animales de su entorno."]'),
('61', '¿QUÉ HACEN LAS PERSONAS?', '40', 'VidaFamilia', '[]'),
('61', 'ENSARTO LOS AROS', '151', 'JugandoAprendo', '["Ensarta los aros en el tubo siguiendo indicaciones de mama.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
('61', 'HAGO TORRES CON OCHO CUBOS', '152', 'JugandoAprendo', '["Coloca 08 cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('61', 'LAMINA 3:DOCE OBJETOS', '243', 'CuentameCuento', '["El niño reconoce y menciona  animales y objetos de su entorno."]'),
('62', 'NUESTRAS DANZAS', '41', 'VidaFamilia', '[]'),
('62', 'ARRASTRO EL GUSANO', '153', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc. Jalando el gusanito.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('62', 'ENSARTO  LOS AROS', '151', 'JugandoAprendo', '["Ensarta los aros en el tubo con precisión siguiendo indicaciones de mama.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
('62', 'LAMINA 2 : NUEVE  OBJETOS', '242', 'CuentameCuento', '["El niño conoce y mencionan  objetos y para qué sirven."]'),
('63', 'CARITA REDONDA', '42', 'VidaFamilia', '[]'),
('63', 'JALO EL COLECTIVO', '154', 'JugandoAprendo', '["Imita sonidos de animales y objetos que conoce):  guau, titi, etc","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: Césped, arena, etc.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('63', 'ARRASTRO EL GUSANO', '153', 'JugandoAprendo', '["Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: bordos, caminitos, etc. Jalando el gusanito ","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('63', 'LIBRO  3 : LOS ANIMALES', '248', 'CuentameCuento', '["El niño escucha y conoce sonidos de los animales de su entorno."]'),
('64', 'ESPEJITO ESPEJITO', '43', 'VidaFamilia', '[]'),
('64', 'CUIDO AL BEBE Y RECONOZCO LAS PARTES DEL CUERPO', '155', 'JugandoAprendo', '["Reconoce y señala  partes de su cuerpo y de otra persona.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('64', 'ME ESCONDO', '144', 'JugandoAprendo', '["Se desplaza por el espacio y reconoce cuando está dentro o afuera ","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\".","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple."]'),
('64', 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce sus  emociones."]'),
('65', '¿QUÉ HACEN LAS PERSONAS?', '40', 'VidaFamilia', '[]'),
('65', 'MI JUGUETE DEBAJO DE LOS PAÑUELOS', '156', 'JugandoAprendo', '["El niño busca los juguetes debajo de los pañuelos","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('65', 'HAGO TORRES CON OCHO CUBOS', '152', 'JugandoAprendo', '["Coloca 08 cubos uno encima de otro","Señala un objeto conocido cuando se lo nombra (10-12 m)","Utiliza \"sus\" palabras otorgándoles significado  (10-12 m)","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('65', 'LIBRO 1: LOS OBJETOS', '256', 'CuentameCuento', '["El niño conoce y nombra  objetos."]'),
('66', 'NUESTRAS DANZAS', '41', 'VidaFamilia', '[]'),
('66', 'RUEDO LAS PELOTAS POR EL TUBO', '157', 'JugandoAprendo', '["Realiza movimientos de mayor precisión con sus manos.  P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: Césped, arena, etc."]'),
('66', 'ROMPECABEZAS 2', '158', 'JugandoAprendo', '["El niño encaja las piezas del rompe cabezas","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos.","Mantiene la atención cuando le narran cuentos muy cortos."]'),
('66', 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce emociones a través de diversos gestos."]'),
('67', 'CARITA REDONDA', '42', 'VidaFamilia', '[]'),
('67', 'ENCAJO EL CUBO PEQUEÑO DENTRO DEL GRANDE', '159', 'JugandoAprendo', '["Encaja el vaso pequeño dentro del vaso grande.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Intenta hacer cosas por sí mismo (ej. Intenta guardar los juguetes, abrocharse el abrigo aunque no lo logre, quitarse la ropa, abrir el lavamanos, manejar la cuchara, beber de una taza, etc.)"]'),
('67', 'ENCESTO LAS PELOTAS', '136', 'JugandoAprendo', '["El niño lanza la pelota hacia el cesto desde una distancia corta","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: Césped, arena, etc.","Lanza objetos a distancia corta (10-12 m)."]'),
('67', 'LAMINA :2 NUEVE OBJETOS', '242', 'CuentameCuento', '[" El niño aprende el nombre de los objetos y para qué sirven."]'),
('68', 'ESPEJITO ESPEJITO', '43', 'VidaFamilia', '[]'),
('68', 'EMPUJO EL JUGUETE HACIENDO ”VRUM”', '160', 'JugandoAprendo', '["Imita sonidos de animales y objetos que conoce:  guau, titi, etc","Se desplaza caminando y manteniendo el equilibrio, sobre diferentes superficies: césped, arena, etc.","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\"."]'),
('68', 'ROMPECABEZAS 2', '158', 'JugandoAprendo', '["Encaja las piezas del rompecabezas.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Pasa páginas gruesas de un libro 2 ó 3 a la vez.","Mantiene la atención cuando le narran cuentos"]'),
('68', 'LIBRO 3 :LOS ANIMALES', '258', 'CuentameCuento', '["El niño escucha y conoce sonidos de los animales de su entorno."]'),
('69', 'FUERA DEL PAÑAL', '44', 'VidaFamilia', '[]'),
('69', 'ARRIBA LAS MARACAS', '161', 'JugandoAprendo', '["El niño imita los movimientos que hace mama usando las marcas y se divierte con ellas moviéndola en diferentes direcciones.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
('69', 'LIBRO 2 : MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce emociones a través de diversos gestos "]'),
('70', 'CONOZCO LAS PARTES  DE MI CUERPO', '45', 'VidaFamilia', '[]'),
('70', 'COLOCA  Y SACA TODOS LOS OBJETOS DE LA BOTELLA', '162', 'JugandoAprendo', '["El niño coloca objetos diferentes en la botella cuando su mama le indica.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan."]'),
('70', 'LAMINA 3 : DOCE OBJETOS', '243', 'CuentameCuento', '[" El niño reconoce los animales y objetos de su entorno."]'),
('71', 'CADA  PARTE HACE ALGO', '46', 'VidaFamilia', '[]'),
('71', 'ENCAJO DOS CUBOS Y DOS VASOS LÓGICOS', '163', 'JugandoAprendo', '["El niño encaja el cubo chico en el cubo grande y el vaso chico en el vaso grande.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Intenta hacer cosas por sí mismo (ej. Intenta guardar los juguetes, abrocharse el abrigo aunque no lo logre, quitarse la ropa, abrir el lavamanos, manejar la cuchara, beber de una taza, etc.)"]'),
('71', 'ROMPECABEZAS 2 FLORES EN UNA MACETA', '158', 'JugandoAprendo', '["Encaja las piezas del rompe cabezas","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Realiza movimientos de mayor precisión con sus manos.  P.E. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
('71', 'LIBRO 4: EL BEBE TIENE HAMBRE', '259', 'CuentameCuento', '["El niño escucha historias sencillas de la vida cotidiana."]'),
('72', 'IGUALES Y DIFERENTES', '47', 'VidaFamilia', '[]'),
('72', 'JALO EL GUSANO HACIA MI', '164', 'JugandoAprendo', '["Resuelve problemas utilizando sus experiencias previas","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan"]'),
('72', 'LIBRO 3 :LOS ANIMALES', '258', 'CuentameCuento', '["El niño escucha y reconoce sonidos de los animales de su entorno."]'),
('73', 'IGUALES  Y DIFERENTES', '47', 'VidaFamilia', '[]'),
('73', 'LANZO LAS ALMOHADAS', '165', 'JugandoAprendo', '["Lanza las almohadas hacia el cesto.","Diferencia características notorias entre los objetos: grande-pequeño, duro-blando, frío-caliente"]'),
('73', 'LAMINA 4 : QUINCE OBJETOS', '244', 'CuentameCuento', '["El niño nombra los alimentos que ve."]'),
('74', 'LO QUE ES IGUAL LO PONEMOS JUNTO', '48', 'VidaFamilia', '[]'),
('74', 'ROMPECABEZAS 3:', '166', 'JugandoAprendo', '["Encaja las piezas del rompecabezas","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Reconoce objetos cotidianos y significativos en ilustraciones"]'),
('74', 'LIBRO 5 : EL POLO SUCIO', '260', 'CuentameCuento', '["El niño escucha una historia sobre  limpio, sucio y mojado."]'),
('75', 'ESTO ES GRANDE  Y ESTO ES PEQUEÑO', '49', 'VidaFamilia', '[]'),
('75', 'MIS CARRITOS “VRUM, VRUM”', '167', 'JugandoAprendo', '["Imita el sonido de los carritos mientras juega con ellos.","Juega cerca a otros niños realizando acciones similares o utilizando materiales","Imita sonidos onomatopéyicos (de animales y objetos que conoce): guau, guau, titi, etc. (13-18 m)"]'),
('75', '¿CÓMO HACEN LOS ANIMALES?', '168', 'JugandoAprendo', '["Imita el sonido que hace los animales que él conoce."," Imita sonidos onomatopéyicos (de animales y objetos que conoce): guau, guau, titi, etc. (13-18 m)","Se mantiene sentado y sin apoyo mientras juega (10-12 m"]'),
('75', 'LAMINA 3 : DOCE OBJETOS', '243', 'CuentameCuento', '["El niño reconoce  características  de los animales y objetos de su entorno."]'),
('76', 'DIGO EL NOMBRE DE LOS ALIMENTOS', '50', 'VidaFamilia', '[]'),
('76', 'PASEO EN EL COLECTIVO', '169', 'JugandoAprendo', '["El niño representa actividades de su vida diaria jugando en el colectivo","Realiza movimientos de mayor precisión con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, , troza con ambas manos","Encaja varias piezas en un tablero, adecuando sus manos y dedos"]'),
('76', 'ROMPECABEZAS 3', '166', 'JugandoAprendo', '["El niño encaja las piezas del rompecabezas.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Reconoce objetos cotidianos y significativos en ilustraciones"]'),
('76', 'HAGO UNA FILA DE CUBOS', '170', 'JugandoAprendo', '["El niño hace una fila con los cubos y lo empuja hacia adelante.","Juega representando actividades de la vida cotidiana (da de comer a la muñeca, maneja el carro, carga la wawa en la lliclla, etc) utilizando objetos diversos para completar sus juegos de imitación."]'),
('76', 'LIBRO 2 MIS EMOCIONES', '257', 'CuentameCuento', '["El niño reconoce emociones a través de diversos gestos."]'),
('77', 'DIGO LAS CARACTERÍSTICAS DE LOS ALIMENTOS', '51', 'VidaFamilia', '[]'),
('77', 'MI JUGUETE EN EL PUÑO DE LA MAMA', '171', 'JugandoAprendo', '["El niño busca la mano de su mama, que está escondido debajo del pañuelo.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","En sus conversaciones se puede distinguir 10 palabras como mínimo","Comprende indicaciones sencillas realizando la acción: entrega la pelota ante la indicación \"dame la pelota\", busca la mano ante la indicación \"búscala\", etc. (13-18 m)."]'),
('77', 'LIBRO 1 : POLO SUCIO', '260', 'CuentameCuento', '["El niño escucha una historia sobre limpio, sucio y mojado."]'),
('78', 'LOS ALIMENTOS TIENEN COLOR', '52', 'VidaFamilia', '[]'),
('78', 'ME DIVIERTO JALANDO EL GUSANITO', '162', 'JugandoAprendo', '["Corre en distintas direcciones jalando el gusanito.","Jala los objetos de un lugar a otro."]'),
('78', 'LIBRO  6 :VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niño escucha una historia de la vida cotidiana"]'),
('79', 'ME AYUDAS A BARRER', '53', 'VidaFamilia', '[]'),
('79', 'LOS ANIMALES HACEN UNA FILA', '173', 'JugandoAprendo', '["El niño coloca a los animales uno al lado de otro mencionando su nombre.","Pregunta el nombre de los objetos que acaba de conocer y los repite","En sus conversaciones se puede distinguir 10 palabras como mínimo."]'),
('79', '¿A DÓNDE SE FUERON LOS ANIMALES?', '173', 'JugandoAprendo', '["Busca los animales, cuando su mama lo esconde."]'),
('79', 'LAMINA 3 : DOCE OBJETOS', '243', 'CuentameCuento', '["El niño reconoce los animales y objetos  de su entorno."]'),
('80', 'ME AYUDAS A LIMPIAR', '54', 'VidaFamilia', '[]'),
('80', 'CUIDO AL BEBE Y APRENDO LAS PARTES DEL CUERPO', '155', 'JugandoAprendo', '["Reconoce las partes gruesas y finas de su cuerpo","Demuestra sentido rítmico moviéndose espontáneamente ante la música."]'),
('80', 'ROMPECABEZAS 3', '166', 'JugandoAprendo', '["El niño encaja las piezas del rompecabezas.","Resuelve problemas utilizando sus experiencias previas: gira la manija para abrir una puerta, jala para destapar algo, encaja una pieza simple.","Reconoce objetos cotidianos y significativos en ilustraciones"]'),
('80', 'LIBRO 5 : ÉL BEBE TIENE HAMBRE', '-3', 'CuentameCuento', '["El niño escucha una historia "]'),
('81', 'MI CUERPO SE ESTÁ MOVIENDO', '55', 'VidaFamilia', '[]'),
('81', 'ENCUENTRO MI JUGUETE DEBAJO DE  PAÑUELOS ARRUGADOS', '174', 'JugandoAprendo', '["Busca objetos conocidos aunque no los tenga a la vista.","Resuelve problemas utilizando sus experiencias previas."]'),
('81', 'LAMINA  4: 15 OBJETOS', '244', 'CuentameCuento', '["El niño menciona características y utilidad de los alimentos."]'),
('82', 'CUANDO ME ASEO  APRENDO MÁS PARTES DE MI CUERPO', '56', 'VidaFamilia', '[]'),
('82', 'ENCAJO  TODOS LOS CUBOS Y LOS VASOS LÓGICOS', '175', 'JugandoAprendo', '["El niño encaja todos los cubos y vasos lógicos.","Realiza movimientos de mayor precisión con sus manos. P.e.: abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
('82', 'ROMPECABEZAS  4', '177', 'JugandoAprendo', '["Encaja las piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
('82', 'LIBRO  5: EL POLO SUCIO', '260', 'CuentameCuento', '["El niño escucha una historia sobre limpio, sucio y mojado.."]'),
('83', 'MI ROPA TIENE COLOR', '57', 'VidaFamilia', '[]'),
('83', 'EL COLECTIVO AVANZA Y SE DETIENE', '176', 'JugandoAprendo', '["El niño jala el colectivo en diferentes direcciones.","Diferencia características notorias entre los objetos: grande-pequeño, duro-blando, frío-caliente.","Juega representando actividades de la vida cotidiana (da de comer a la muñeca, maneja el carro, carga la wawa en la lliclla, etc.) utilizando objetos diversos para completar sus juegos de imitación."]'),
('83', 'LIBRO 4: EL BEBE TIENE HAMBRE', '259', 'CuentameCuento', '[" El niño escucha historias de la vida cotidiana."]'),
('84', '¿ESTÁ LLENO O VACÍO?', '58', 'VidaFamilia', '[]'),
('84', 'RUEDO LAS PELOTAS POR EL TUBO', '157', 'JugandoAprendo', '["El niño hace rodar la pelota por el tubo inclinado."]'),
('84', 'ROMPECABEZAS 4', '177', 'JugandoAprendo', '["Encaja piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
('84', 'LIBRO 6: VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niño  escucha  una historia sobre la vida cotidiana."]'),
('85', 'ENCUENTRO TESOROS POR DONDE CAMINO', '59', 'VidaFamilia', '[]'),
('85', 'EXPERIMENTANDO CON NOCIONES “ENCIMA  Y DEBAJO”', '178', 'JugandoAprendo', '["El niño coloca encima o debajo  de la mesa.","Muestra interés e iniciativa en la relación con los adultos, repitiendo acciones que le agradan.","Comprende indicaciones sencillas realizando la acción:  Entrega la pelota ante la indicación \"dame la pelota\", empuja el juguete, etc. (13-18 m)"]'),
('85', 'LIBRO 4: ÉL BEBE TIENE HAMBRE', '259', 'CuentameCuento', '["El niño  escucha  una historia sobre la vida cotidiana."]'),
('86', 'SIMÓN DICE…', '60', 'VidaFamilia', '[]'),
('86', 'LOS ANIMALES  HACEN UNA FILA', '173', 'JugandoAprendo', '["El niño coloca a los animales uno al lado de otro mencionando su nombre.","Pregunta el nombre de los objetos que acaba de conocer y los repite."]'),
('86', 'ROMPECABEZAS  4', '177', 'JugandoAprendo', '["Encaja las piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
('86', 'LAMINA 3:12 OBJETOS', '243', 'CuentameCuento', '["El niño reconozca  los animales y objetos  de su entorno."]'),
('87', 'OTRO SIMÓN DICE …', '61', 'VidaFamilia', '[]'),
('87', 'CAMINO SIN  CHOCARME', '179', 'JugandoAprendo', '["El niño camina entre las almohadas sin chocarse","Juega representando actividades de la vida cotidiana (da de comer a la muñeca, maneja el carro, carga la wawa en la lliclla, etc.) utilizando objetos diversos para completar sus juegos de imitación."]'),
('87', 'JUEGO CON LOS BLOQUES  DE DIFERENTES  FORMAS', '180', 'JugandoAprendo', '["El niño diferencia el bloque según su tamaño.","Juega representando actividades de la vida cotidiana (da de comer a la muñeca, maneja el carro, carga la wawa en la lliclla, etc.) utilizando objetos diversos para completar sus juegos de imitación."]'),
('87', 'LAMINA 4: 15 ALIMENTOS', '244', 'CuentameCuento', '["El niño menciona    las características   de los alimentos."]'),
('88', 'LLAMEMOS A …', '62', 'VidaFamilia', '[]'),
('88', 'ENCESTO LAS PELOTAS', '136', 'JugandoAprendo', '["Lanza la pelota hacia una dirección determinada","Lanza objetos a distancia corta (10-12 m"]'),
('88', 'ROMPECABEZAS 4', '177', 'JugandoAprendo', '["Encaja piezas del rompecabezas.","Encaja una pieza en una base fija (una figura con contorno regular) adecuando sus manos y dedos (13-18 m)"]'),
('88', 'JUEGO CON DIEZ CUBOS', '181', 'JugandoAprendo', '["Coloca cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción (13-18 m)"]'),
('88', 'LIBRO 5: EL POLO SUCIO', '260', 'CuentameCuento', '["El niño escucha  una historia sobre limpio, sucio y mojado."]'),
('89', 'VEO, VEO.', '63', 'VidaFamilia', '[]'),
('89', 'EL  COLECTIVO VA LEJOS Y DEJA A TODOS LOS PASAJEROS', '182', 'JugandoAprendo', '["El niño representa actividades de su vida diaria jugando con el carrito.","Jala los objetos de un lugar a otro."]'),
('89', 'LAMINA 4: 15 OBJETOS', '244', 'CuentameCuento', '["El niño menciona  las características de  animales."]'),
('90', 'VEO, VEO', '63', 'VidaFamilia', '[]'),
('90', 'ROMPECABEZAS 5', '183', 'JugandoAprendo', '["Encaja las piezas del rompecabezas","Diferencia características notorias entre los objetos: grande-pequeño, duro-blando, frío-caliente"]'),
('90', 'EL POLO SUCIO', '260', 'CuentameCuento', '["El niño sigue la secuencia  de la historia reconociendo  limpio, sucio y mojado."]'),
('91', 'MI BANDA', '64', 'VidaFamilia', '[]'),
('91', 'SOY FUERTE', '184', 'JugandoAprendo', '["El niño identifica la diferencia entre pesado y liviano","Camina manteniendo el equilibrio sobre diferentes planos sin caerse:  Inclinado, ondulado, etc."]'),
('91', 'JUEGO CON DIEZ CUBOS', '181', 'JugandoAprendo', '["Coloca cubos uno encima de otro","Comprende indicaciones sencillas realizando la acción (13-18 m)"]'),
('91', 'LIBRO 6:VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niño  nombra los alimentos más comunes  y las acciones de ir a comprarlos."]'),
('92', 'MI BANDA', '64', 'VidaFamilia', '[]'),
('92', 'ME  DIVIERTO JALANDO EL GUSANITO RÁPIDO Y LENTO', '185', 'JugandoAprendo', '["Corre en distintas direcciones jalando el gusanito.","Comprende indicaciones sencillas realizando la acción (13-18 m)"]'),
('92', 'ROMPECABEZAS 6', '186', 'JugandoAprendo', '["Coloca cubos uno encima de otro","En sus conversaciones se puede distinguir 10 palabras como mínimo.","Comprende indicaciones sencillas realizando la accion (13-18 m)"]'),
('92', 'LIBRO 4: EL BEBE TIENE HAMBRE', '259', 'CuentameCuento', '["El niño escucha historias y describe las situaciones  del  cuento."]'),
('93', 'JUGAMOS A BAÑAR LOS MUÑECOS', '65', 'VidaFamilia', '[]'),
('93', 'DERRUMBO LA PARED', '187', 'JugandoAprendo', '["Lanza un objeto hacia la pared de cubos para derrumbarla.","Realiza movimientos de mayor precisión con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos"]'),
('93', 'TÍTERE CONVERSADOR', '188', 'JugandoAprendo', '["Se expresa por medio de frases de dos o tres palabras.","Conoce algunas reglas básicas aunque no siempre las sigue (p.e.: no empujar al amigo, esperar su turno, guardar al terminar de jugar)","En sus conversaciones se puede distinguir 10 palabras como mínimo"]'),
('93', 'ESCENA 1: LA POSTA MEDICA', '245', 'CuentameCuento', '["El niño reconoce las acciones realizadas en una posta médica y quienes trabajan ahí."]'),
('94', 'GRANDE  PEQUEÑO', '66', 'VidaFamilia', '[]'),
('94', 'HACEMOS UN SOBRE', '189', 'JugandoAprendo', '["Garabetea libremente.","Realiza movimientos de mayor precisión con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos"]'),
('94', '¿DÓNDE ESTÁ MI  CARRO?', '190', 'JugandoAprendo', '["El niño representa actividades de su vida diaria jugando con el carrito.","Se desplaza por el espacio reconociendo la ubicación de los objetos (sabe dónde se guardan los juguetes, arriba-abajo la ubicación de los muebles)."]'),
('94', 'LIBRO 6: VAMOS A LA FERIA', '261', 'CuentameCuento', '["El niño  nombra los alimentos más comunes y las acciones de ir a comprarlos."]'),
('95', 'ESTO USA PAPA  Y ESTO USA MAMA', '67', 'VidaFamilia', '[]'),
('95', 'JUEGO  A COSTAR AL  BEBE', '191', 'JugandoAprendo', '["El niño representa actividades de su vida diaria jugando con el muñeco.","Reconoce las partes gruesas y finas de su cuerpo"]'),
('95', 'LOTERÍA  1: LA FLOR DE TAPAS', '192', 'JugandoAprendo', '["Agrupa objetos iguales.","Reconoce objetos cotidianos y significativos en ilustraciones."]'),
('95', 'LIBRO 7: MI DÍA', '262', 'CuentameCuento', '["El niño identifica y reconoce las actividades que se realizan durante el día."]'),
('96', '¿QUÉ RARO?', '68', 'VidaFamilia', '[]'),
('96', 'LA FLOR DE TAPAS', '193', 'JugandoAprendo', '["Resuelve problemas utilizando sus experiencias previas","Realiza movimientos de mayor precisión con sus manos. P.e. abotona, desabotona, sube y baja cierres, arruga papeles, troza con ambas manos."]'),
('96', 'ROMPECABEZAS 7', '194', 'JugandoAprendo', '["Encaja varias piezas en un tablero adecuando sus manos y dedos.","Reconoce las partes gruesas y finas de su cuerpo","En sus conversaciones se puede distinguir 10 palabras como mínimo."]'),
('96', 'ESCENA 2:LA CHACRA', '246', 'CuentameCuento', '["El niño describe actividades que realiza su familia en la chacra."]'),
('97', 'CONOZCO LOS NOMBRES DE LAS PRENDAS DE VESTIR', '69', 'VidaFamilia', '[]'),
('97', 'HAGO UN COLLAR', '195', 'JugandoAprendo', '["Ensarta cuentas con orificios grandes.","Realiza movimientos de mayor precisión con sus dedos. P.e. abotona, desabotona, abrocha, desabrocha, sube y baja cierres, rasga con los dedos, abolilla, inserta objetos en ranura."]'),
('97', 'JUEGO CON LOS BLOQUES  DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m).","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
('97', 'MIS PRIMEROS  DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
('97', 'ESCENA 3: LA PLAZA PRINCIPAL /LA PESCA', '274', 'CuentameCuento', '["La mamá le cuente una historia de la plaza de su pueblo al niño."]'),
('98', '¿QUÉ COSAS  FALTAN?', '70', 'VidaFamilia', '[]'),
('98', 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
('98', 'TÍTERE CONVERSADOR', '188', 'JugandoAprendo', '["Se expresa utilizando frases de 2 o 3  palabras","Sigue reglas básicas: Guardar juguetes, pasar de un espacio a otro cuando se le indique, no pegar al otro, etc."]'),
('98', 'ESCENA 1: LA POSTA MEDICA', '245', 'CuentameCuento', '["El niño escucha y relaciona el relato de la posta medica"]'),
('99', '¿QUÉ SERÁ?', '71', 'VidaFamilia', '[]'),
('99', 'EL COLECTIVO VA LEJOS  Y DEJA A TODOS LOS PASAJEROS', '182', 'JugandoAprendo', '["El niño representa actividades de su vida diaria jugando con el carrito.","Dramatiza situaciones conocidas, que contienen pequeños argumentos."]'),
('99', 'LOTERÍA 1: LA FLOR DE TAPAS', '193', 'JugandoAprendo', '["Resuelve problemas utilizando sus experiencias previas","Nombra objetos familiares que observa en ilustraciones"]'),
('99', 'ROMPECABEZAS  7', '194', 'JugandoAprendo', '["Encaja varias piezas en un tablero adecuando sus manos y dedos.","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m)"]'),
('99', 'LIBRO 7: MI DÍA', '262', 'CuentameCuento', '["El niño reconoce y asocia las rutinas del día."]'),
('100', '¿QUÉ  SERÁ? ', '76', 'VidaFamilia', '[]'),
('100', 'JUEGO LA COMIDITA', '198', 'JugandoAprendo', '["Dramatiza situaciones conocidas de vida diaria jugando a la comidita","Colabora con iniciativa en tareas sencillas: guardar juguetes, botar basura, poner platos en la mesa, etc.","Relaciona objetos según su función: peine para peinarse, taza para tomar, etc."]'),
('100', 'ROMPECABEZAS 7', '194', 'JugandoAprendo', '["Encaja varias piezas en un tablero adecuando sus manos y dedos.","En sus conversaciones se puede distinguir 10 palabras como mínimo."]'),
('100', 'LIBRO 8: A MARÍA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niño asocia las escena con su vida cotidiana"]'),
('101', 'RECORDANDO LO QUE HICE HOY', '72', 'VidaFamilia', '[]'),
('101', 'CONSTRUYO CORRALES  PARA LOS ANIMALES', '199', 'JugandoAprendo', '["Utiliza diferentes objetos para hacer un corral para los animales","Mantiene la atención cuando le narra cuentos muy cortos (13-18 m)"]'),
('101', 'LIBRO 8: A MARÍA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niño asocia las escenas con su vida cotidiana."]'),
('102', 'RECORDANDO LO QUE HICE HOY', '72', 'VidaFamilia', '[]'),
('102', 'MIS CARROS VAN Y VAN', '200', 'JugandoAprendo', '["Dramatiza situaciones conocidas de vida diaria jugando  con el carrito","Diferencia características notorias entre objetos: grande-pequeño (19-24 m)."]'),
('102', 'MIS  PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('102', 'EXPERIMENTO CON LA CRAYOLA', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('102', 'ESCENA 1: LA POSTA MEDICA', '245', 'CuentameCuento', '["El niño escucha y relaciona el relato de la posta medica"]'),
('103', '¿DÍA, TARDE  O NOCHE?', '73', 'VidaFamilia', '[]'),
('103', 'LA CASITA DE TAPAS', '201', 'JugandoAprendo', '["Realiza movimientos de mayor precisión con sus manos para armar una casita  con tapas.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('103', 'LOTERÍA 2: MUEBLES', '202', 'JugandoAprendo', '["Coloca figuras que corresponden en la lámina ","Agrupa objetos iguales (19-24 m)"]'),
('103', 'LIBRO 9 JUAN PREGUNTA ¿CÓMO ES', '264', 'CuentameCuento', '["El niño escucha las explicaciones y el ¿Por qué? de las cosas."]'),
('104', '¿DÍA, TARDE O NOCHE?', '73', 'VidaFamilia', '[]'),
('104', 'ROMPECABEZAS 8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('104', 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('104', 'ESCENA 2: LA CHACRA', '246', 'CuentameCuento', '["El niño escucha y relaciona el relato de la chacra de lo que realiza papá y mamá."]'),
('105', 'AYUDO  A TENER LIMPIA MI ROPITA', '74', 'VidaFamilia', '[]'),
('105', 'JUEGO CON ÉL BEBE  Y HABLO SOBRE LAS PRENDAS DE  VESTIR', '204', 'JugandoAprendo', '["Dramatiza situaciones de su vida diaria, mientras juega con el muñeco","Realiza movimientos de mayor precisión con sus dedos. P.e. abotona, desabotona, abrocha, desabrocha, sube y baja cierres, rasga con los dedos, abolilla, insera objetos en ranuras"]'),
('105', 'JUEGO CON LOS BLOQUES DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego.","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m).","Se expresa por medio de frases de dos o tres palabras (19-24 m)"]'),
('105', 'LIBRO 7: MI DÍA', '262', 'CuentameCuento', '["El niño reconoce y asocia las rutinas del día."]'),
('106', 'AYUDO A TENER LIMPIA MI ROPITA', '74', 'VidaFamilia', '[]'),
('106', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('106', 'LIBRO 8: A MARÍA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niño asocia las escena con su vida cotidiana"]'),
('107', 'AYUDO A ORDENAR LA ROPA', '75', 'VidaFamilia', '[]'),
('107', 'LOTERÍA  2', '202', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos.","Agrupa objetos iguales (19-24 m)"]'),
('107', 'ESCENA 3: LA PLAZA PRINCIPAL/LA PESCA', '247', 'CuentameCuento', '["Que la mamá le cuente una historia de la plaza de su pueblo."]'),
('108', 'AYUDO A ORDENAR LA ROPA', '75', 'VidaFamilia', '[]'),
('108', 'JUEGO  A LA COMIDITA', '198', 'JugandoAprendo', '["Dramatiza situaciones conocidas de su vida diaria jugando a la comidita","Colabora con iniciativa en tareas sencillas: guarda juguetes, botar la basura, poner platos en la mesa, etc.","Relaciona objetos según su función: peine para peinarse, taza para tomar, etc."]'),
('108', 'ROMPECABEZAS  8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('108', 'LIBRO 9: JUAN PREGUNTA ¿CÓMO ES?', '264', 'CuentameCuento', '["El niño escuche las explicaciones y el ¿Por qué? De las cosas."]'),
('109', '¿ESTO ES TUYO?', '76', 'VidaFamilia', '[]'),
('109', 'HAGO UN COLLAR DE COLORES', '205', 'JugandoAprendo', '["Ensarta cuentas en con orificios pequeños."]'),
('109', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('109', 'JUAN PREGUNTA ¿CÓMO ES?', '264', 'CuentameCuento', '["El niño escucha las explicaciones y el ¿Por qué? de las cosas."]'),
('110', '¿ESTO ES TUYO?', '76', 'VidaFamilia', '[]'),
('110', '¿QUÉ HAY  DENTRO DE LA BOLSA?', '206', 'JugandoAprendo', '["Sigue indicaciones de la mama  mientras juega."]'),
('110', 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
('110', 'ESCENA 4: LA FIESTA PATRONAL', '248', 'CuentameCuento', '["El niño escucha y relaciona el relato de la fiesta patronal."]'),
('111', 'AYUDO A COCINAR', '77', 'VidaFamilia', '[]'),
('111', 'MIS CARROS VAN Y VAN', '202', 'JugandoAprendo', '["El niño diferencia el carro grande y el carro pequeño."]'),
('111', 'LOTERÍA 3: 6 OBJETOS FAMILIARES', '208', 'CuentameCuento', '["Encaja varias piezas en un tablero, según la lámina.","Relaciona objetos según su función: peine para peinarse, taza para tomar, etc.","Agrupa objetos iguales (19-24 m)"]'),
('111', 'ESCENA 2: LA CHACRA', '246', 'CuentameCuento', '["El niño escucha y relaciona el relato de la chacra de lo que realiza papá y mamá."]'),
('112', 'AYUDO A COCINAR', '77', 'VidaFamilia', '[]'),
('112', 'PREPARAMOS  LA MESA PARA COMER', '207', 'JugandoAprendo', '["Relaciona la función de los objetos mientras se prepara la mesa para comer."]'),
('112', 'ROMPECABEZAS 8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('112', 'LIBRO 8: A MARÍA LE GUSTA JUGAR', '264', 'CuentameCuento', '["El niño asocia las escenas con su vida cotidiana."]'),
('113', 'A GUARDAR A GUARDAR', '78', 'VidaFamilia', '[]'),
('113', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
('113', 'LOS PASAJEROS DE COLORES SE PASEAN', '209', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego.","Encaja varias piezas en un tablero, adecuando sus manos y dedos"]'),
('113', 'LIBRO 10 MARÍA PREGUNTA ¿DÓNDE  ESTÁ?', '265', 'CuentameCuento', '["El niño escucha atentamente el cuento."]'),
('114', 'A GUARDAR', '78', 'VidaFamilia', '[]'),
('114', 'LA CASITA DE TAPAS', '201', 'JugandoAprendo', '["Realiza movimientos de mayor precisión con sus manos para armar una casita  con tapas.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('114', 'ROMPECABEZAS 8', '203', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('114', 'LIBRO 7: MI DÍA', '262', 'CuentameCuento', '["El niño reconoce y asocia las rutinas del día."]'),
('115', 'ACOMPAÑA A MAMA EN LA CHACRA', '79', 'VidaFamilia', '[]'),
('115', 'SACO UNO, SACO TODOS', '210', 'JugandoAprendo', '["Diferencia entre lleno y vacío – mucho – y poco.","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m)"]'),
('115', 'LOTERÍA 3: 6 OBJETOS FAMILIARES', '208', 'CuentameCuento', '["Encaja objetos según la lámina","Relaciona objetos según su función: peine para peinarse, taza para tomar, etc.","Agrupa objetos iguales (19-24 m)"]'),
('115', 'ESCENA 3: LA PLAZA PRINCIPAL / LA PESCA', '274', 'CuentameCuento', '["El niño escucha y relaciona el relato de la plaza principal."]'),
('116', 'ACOMPAÑA A MAMA EN LA CHACRA.', '79', 'VidaFamilia', '[]'),
('116', 'JUEGO CON LOS BLOQUES  DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m).","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
('116', 'LOTERIA 4', '211', 'JugandoAprendo', '["Encaja objetos según la lámina","Agrupa objetos iguales (19-24 m)"]'),
('116', 'ESCENA 4: LA FIESTA  PATRONAL', '211', 'CuentameCuento', '["El niño escucha y relaciona el relato de la fiesta patronal."]'),
('117', '¡QUE LINDA LA NATURALEZA!', '80', 'VidaFamilia', '[]'),
('117', 'JUEGO A BAÑAR A LA MUÑECA', '212', 'JugandoAprendo', '["Dramatiza situaciones conocidas de su vida diaria mientras baña a la muñeca","Juega representando actividades de la vida cotidiana (da de comer a la muñeca, baña a la muñeca, imita el carro) utilizando diversos objetos para completar sus juegos de imitación (19-24 m)"]'),
('117', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('117', 'LIBRO 10 MARÍA PREGUNTA ¿DÓNDE  ESTÁ?', '265', 'CuentameCuento', '["El niño escucha atentamente."]'),
('118', 'QUE LINDA LA NATURALEZA', '80', 'VidaFamilia', '[]'),
('118', 'IMITO A MAMA', '213', 'JugandoAprendo', '["Imita las acciones que hace mama.","Comprende indicaciones sencillas realizando la acción (13-18 m)"]'),
('118', 'ROMPECABEZAS', '214', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Describe escenas sencillas que observa en una lámina"]'),
('118', 'SECUENCIA 1: CAMBIO DE ROPA', '249', 'CuentameCuento', '["Mamá describe al niño  los pasos de cambiarse de ropa."]'),
('119', ' “EL LÍDER”', '81', 'VidaFamilia', '[]'),
('119', 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
('119', 'LOTERÍA 5', '215', 'CuentameCuento', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
('119', 'SECUENCIA 2 EL CEPILLADO DE LOS DIENTES', '250', 'CuentameCuento', '["El niño observa los pasos de cepillado de dientes"]'),
('120', 'EL LÍDER”', '81', 'VidaFamilia', '[]'),
('120', 'MI CARRO SE PASEA', '216', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Comprende indicaciones sencillas realizando la acción (13-18 m)"]'),
('120', 'ROMPECABEZAS 10', '217', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Se expresa por medio de frases de dos o tres palabras"]'),
('120', 'SECUENCIA 4 SEMBRAMOS PARA COMER', '252', 'CuentameCuento', '["El niño observa y escucha  los pasos de sembrando."]'),
('121', '¿POR DÓNDE NOS FUIMOS?', '82', 'VidaFamilia', '[]'),
('121', 'LOS ANIMALES ESTÁN  CERCA Y LEJOS  DE SU CASA', '218', 'JugandoAprendo', '["Corre en diferentes direcciones sin caerse ni chocarse.","Transforma los objetos con creatividad durante el juego: Utiliza una manta como capa, etc"]'),
('121', 'JUEGO CON LOS BLOQUES DE DIFERENTES  FORMAS', '180', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
('121', 'LIBRO 11:  MARÍA Y JUAN JUEGAN CON LOS COLORES', '266', 'CuentameCuento', '["El niño(a) conversa con mamá y describe imágenes."]'),
('122', '¿POR DÓNDE  NOS FUIMOS?', '82', 'VidaFamilia', '[]'),
('122', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica."]'),
('122', 'EL COLECTIVO HACE LO QUE LE PEDIMOS', '219', 'JugandoAprendo', '["El niño hace correr o parar al carrito cuando mamá le indica.","Comprende indicaciones sencillas realizando la acción"]'),
('122', 'MIS CARROS  VAN POR EL CAMINO', '220', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Realiza movimientos de mayor precisión con sus dedos. P.e. abotona, desabotona, abrocha, desabrocha, sube y baja cierres, rasga con los dedos, abolilla, insera objetos en ranuras","Construye diversas formas: con bloques, piezas de construcción"]'),
('122', 'ESCENA 3:  LA PLAZA PRINCIPAL ', '247', 'CuentameCuento', '["La niña(o) observa imágenes y conversa con mamá."]'),
('123', 'MANO  SOBRE LA MANO', '83', 'VidaFamilia', '[]'),
('123', 'HAGO UN COLLAR CON TODAS LAS TAPAS', '221', 'JugandoAprendo', '["Ensarta cuentas en con orificios pequeños","Apila objetos uno encima de otros con más de tres elementos (13-18 m)"]'),
('123', 'LOTERÍA 5', '215', 'CuentameCuento', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
('123', 'LIBRO 9 JUAN PREGUNTA ¿CÓMO ES?', '264', 'CuentameCuento', '["El niño describe imágenes  del cuento."]'),
('124', 'MANO SOBRE  LA MANO', '83', 'VidaFamilia', '[]'),
('124', 'MUEVO LA ALMOHADA', '222', 'JugandoAprendo', '["Mantiene por breves momentos el equilibrio parado en un pie","Comprende indicaciones sencillas realizando la acción (13-18 m)."]'),
('124', 'ROMPECABEZAS 10', '217', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Se expresa por medio de frases de dos o tres palabras"]'),
('124', 'ESCENA 5: LA FIESTA PATRONAL', '248', 'CuentameCuento', '["El niño observa imágenes y conversa con mamá."]'),
('125', 'SEMILLAS DE COLORES', '84', 'VidaFamilia', '[]'),
('125', 'MIS PRIMEROS  DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('125', 'ROMPECABEZAS 11', '223', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Se expresa por medio de frases de dos o tres palabras"]'),
('125', 'SECUENCIA 7: VAMOS A PASTOREAR', '255', 'CuentameCuento', '["El niño mira y describe la secuencia de  imágenes"]'),
('126', 'SEMILLAS DE COLORES', '84', 'VidaFamilia', '[]'),
('126', 'LOS ANIMALES ESTÁN CERCA Y LEJOS DE SU CASA', '218', 'JugandoAprendo', '["Corre en diferentes direcciones sin caerse ni chocarse.","Transforma los objetos con creatividad durante el juego: Utiliza una manta como capa, etc."]'),
('126', 'LOTERÍA 6', '224', 'JugandoAprendo', '["Utiliza cuantificadores como mucho-poco, uno-ninguno.","Agrupa objetos iguales (19-24 m)"]'),
('126', 'SECUENCIA 5:  COMPRAMOS PESCADO CON PAPÁ', '250', 'CuentameCuento', '["El niño conversa con mamá y Describe  la secuencia. "]'),
('127', 'JUGAMOS CON LA PELOTA', '85', 'VidaFamilia', '[]'),
('127', 'ADIVINA QUE  ES', '225', 'JugandoAprendo', '["Reconoce un objeto a partir del olor, sabor, textura, sonido aún sin verlo","Busca objetos conocidos aunque no los tenga a la vista (19-24m)"]'),
('127', 'DIBUJA CON MAMÁ', '197', 'CuentameCuento', '["Garabatea libremente con mayor control de su movimiento.","Nombra objetos familiares que observa en ilustraciones"]'),
('127', 'SECUENCIA 6: LAVAMOS LA ROPA', '266', 'CuentameCuento', '["El niño escucha con atención lo que le cuenta mamá."]'),
('128', 'JUGAMOS CON LA PELOTA', '85', 'VidaFamilia', '[]'),
('128', 'LA CASITA DE TAPAS', '201', 'JugandoAprendo', '["Coloca las tapas siguiendo la lámina de la casita.","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('128', 'LOTERÍA 6:  MUCHOS POCOS', '224', 'JugandoAprendo', '["Utiliza cuantificadores como mucho-poco, uno-ninguno","Agrupa objetos iguales (19-24 m)"]'),
('128', 'SECUENCIA 3: TEJEMOS UNA CHOMPA', '251', 'CuentameCuento', '["Mamá describe lámina  contando la historia de la chompa."]'),
('129', 'COMO LOS CONEJITOS', '86', 'VidaFamilia', '[]'),
('129', 'HAGO DISTINTOS COLLARES', '226', 'JugandoAprendo', '["Ensarta cuentas en con orificios pequeños","Comprende indicaciones sencillas realizando la acción (13-18 m)"]'),
('129', 'LOTERÍA 7', '227', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
('129', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento.","Expresa de manera comprensible sus vivencias"]'),
('129', 'SECUENCIA 7: VAMOS A PASTOREAR', '255', 'CuentameCuento', '["El niño mira y describe la secuencia de  imágenes"]'),
('130', 'COMO LOS CONEJITOS', '86', 'VidaFamilia', '[]'),
('130', 'EL CARRO  VA LEJOS POR EL CAMINO', '228', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Construye diversas formas: con bloques, piezas de construcción"]'),
('130', 'JUEGO CON LOS  BLOQUES DE DIFERENTES FORMAS', '180', 'JugandoAprendo', '["El Transforma los objetos con creatividad durante el juego","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
('130', 'SECUENCIA 2: EL CEPILLADO DE LOS DIENTES', '250', 'CuentameCuento', '["Mamá conversa con el niño(a) acerca del aseo."]'),
('131', 'LAS CHAPADAS', '87', 'VidaFamilia', '[]'),
('131', '¿CUÁNTOS PASAJEROS HAY EN EL COLECTIVO?', '229', 'JugandoAprendo', '["Transforma los objetos con creatividad durante el juego","Dramatiza situaciones conocidas, que contienen pequeños argumentos"]'),
('131', 'ROMPECABEZAS 11', '223', 'CuentameCuento', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
('131', 'LIBRO 11: MARÍA Y JUAN JUEGAN CON COLORES', '266', 'CuentameCuento', '["El niño(a) conversa con mamá y describe imágenes."]'),
('132', 'LAS CHAPADAS', '87', 'VidaFamilia', '[]'),
('132', 'COCINAMOS', '230', 'JugandoAprendo', '["Dramatiza situaciones conocidas de su vida diría mientras juegan a la cocinita.","Juega representando actividades cotidianas de la vida diaria utilizando objetos diversos para completar sus juegos de imitación (19-24 m)","Imita acciones rutinarias que realiza el adulto como: barrer, planchar, cocinar, etc. (13-18 m)"]'),
('132', 'LOTERÍA  7', '227', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
('132', 'SECUENCIA 3: TEJEMOS UNA CHOMPA ', '251', 'CuentameCuento', '["Mamá describe lámina  contando la historia de la chompa."]'),
('133', 'TOCO, TOCO  LO QUE NOMBRO', '88', 'VidaFamilia', '[]'),
('133', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('133', '¿QUÉ SERÁ?', '231', 'JugandoAprendo', '["Reconoce un objeto a partir del olor, sabor, textura, sonido aún sin verlo","Busca objetos conocidos aunque no los tenga a la vista (19-24m)"]'),
('133', 'LIBRO 10: MARÍA PREGUNTA ¿DÓNDE ESTÁ?', '265', 'CuentameCuento', '["El niño(a) Conversa con su mamá"]'),
('134', 'TOCA, TOCA LO QUE NOMBRO', '88', 'VidaFamilia', '[]'),
('134', '¿CÓMO SE SIENTE ÉL BEBE?', '232', 'JugandoAprendo', '["Expresa de manera comprensible sus vivencias diarias.","Dramatiza situaciones conocidas, que contienen pequeños argumentos"]'),
('134', 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Nombra objetos familiares que observa en ilustraciones"]'),
('134', 'LIBRO 11: MARÍA Y JUAN JUEGAN CON COLORES', '266', 'CuentameCuento', '["El niño(a) conversa con mamá y describe imágenes."]'),
('135', 'VEO, VEO ¿QUÉ VEZ?', '89', 'VidaFamilia', '[]'),
('135', 'EL GUSANO DE TAPITAS', '233', 'JugandoAprendo', '["Realiza movimientos de mayor precisión con sus dedos.","Comprende indicaciones sencillas realizando la acción (13-18 m) un poco forzada Comprende indicaciones sencillas realizando la acción (13-18 m) "]'),
('135', 'SECUENCIA 4:  SEMBRAMOS PARA COMER', '252', 'CuentameCuento', '["El niño mira la lámina y relaciona con el trabajo de papá."]'),
('136', 'VEO, VEO ¿QUÉ VEZ?', '89', 'VidaFamilia', '[]'),
('136', 'ROMPECABEZAS12: LA NIÑA', '234', 'JugandoAprendo', '["Expresa de manera comprensible sus vivencias diarias","Comprende indicaciones sencillas realizando la acción (13-18 m) un poco forzada"]'),
('136', 'LOTERÍA 7 LAS ACCIONES DEL PERRO', '227', 'JugandoAprendo', '["El niño observa las acciones del perro y empareja con las cartillas."]'),
('136', 'SECUENCIA 5 COMPRAMOS PESCADO CON PAPÁ', '253', 'CuentameCuento', '["El niño conversa con mamá y Describe  la secuencia. "]'),
('137', 'ENSALADA DE FRUTAS', '90', 'VidaFamilia', '[]'),
('137', 'LOS  ANIMALES  EN EL CAMPO', '235', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Agrupa objetos iguales (19-24 m)"]'),
('137', 'SECUENCIA 6: LAVAMOS LA ROPA', '254', 'CuentameCuento', '["El niño escucha con atención lo que le cuenta mamá."]'),
('138', 'ENSALADA DE  FRUTAS', '90', 'VidaFamilia', '[]'),
('138', 'LOTERÍA 8', '236', 'JugandoAprendo', '["Repite juego de palabras, rimas, canciones sencillas","Imita sonidos onomatopéyicos (de animales y objetos que conoce)(13-18 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)"]'),
('138', 'SECUENCIA 4: SEMBRAMOS PARA COMER', '252', 'CuentameCuento', '["Mamá conversa con el niño(a) acerca  de los alimentos que siembra y cosecha."]'),
('139', 'AYER HOY', '91', 'VidaFamilia', '[]'),
('139', 'LE DOY DE COMER A LA MUÑECA', '237', 'JugandoAprendo', '["Dramatiza situaciones conocidas, que contienen pequeños argumentos","Se expresa por medio de frases de dos o tres palabras (19-24 m)"]'),
('139', 'ROMPECABEZAS 12', '234', 'JugandoAprendo', '["Expresa de manera comprensible sus vivencias o comprende indicaciones sencillas"]'),
('139', 'LIBRO 8: A MARÍA LE GUSTA JUGAR', '263', 'CuentameCuento', '["El niño observa las imágenes y conversa con mamá."]'),
('140', 'AYER , HOY', '91', 'VidaFamilia', '[]'),
('140', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('140', 'LOTERÍA 8', '236', 'JugandoAprendo', '["Nombra objetos familiares que observa en ilustraciones","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('140', 'LIBRO 7: MI DÍA', '262', 'CuentameCuento', '["El niño conversa con mamá  acerca del cuento"]'),
('141', 'AYUDO  A SERVIR LA MESA', '92', 'VidaFamilia', '[]'),
('141', 'LOS  ANIMALES  EN EL CAMPO', '235', 'JugandoAprendo', '["Imita el sonido de los animales","Imita sonidos onomatopéyicos (de animales y objetos que conoce)(13-18 m)","Se expresa por medio de frases de dos o tres palabras(19-24 m)","En sus conversaciones se puede distinguir 10 palabras como mínimo (19-24 m)"]'),
('141', 'LOTERÍA  8', '236', 'JugandoAprendo', '["Nombra objetos familiares que observa en ilustraciones","Reconoce objetos cotidianos y significativos en ilustraciones (19-24 m)"]'),
('141', 'LIBRO 9: JUAN PREGUNTA ¿CÓMO ES?', '264', 'CuentameCuento', '["El niño conversa con mamá y disfruta del cuento."]'),
('142', 'AYUDO A SERVIR LA MESA', '92', 'VidaFamilia', '[]'),
('142', 'JUEGO A LA MAMÁ  Y  EL PAPÁ', '238', 'JugandoAprendo', '["Dramatiza situaciones conocidas, que contienen pequeños argumentos","Juega representando actividades de la vida cotidiana (da de comer a la muñeca, maneja el carro) utilizando objetos diversos para completar sus juegos de imitación (19-24 m)","Imita acciones rutinarias que realiza el adulto (13-18 m)"]'),
('142', 'LOTERÍA  9: CANTIDAD', '239', 'JugandoAprendo', '["Utiliza cuantificadores como mucho-poco, uno-ninguno","Agrupa objetos iguales (19-24 m)"]'),
('142', 'LIBRO 10: MARÍA PREGUNTA ¿DÓNDE ESTÁ?', '265', 'CuentameCuento', '["El niño conversa con mamá y disfruta del cuento."]'),
('143', 'UN ALMUERZO PARA MIS INVITADOS', '93', 'VidaFamilia', '[]'),
('143', 'EL GUSANITO  DE TAPITAS', '233', 'JugandoAprendo', '["Realiza movimientos de mayor precisión con sus dedos.","Comprende indicaciones sencillas realizando la acción (13-18 m) un poco forzada","Agrupa objetos iguales (19-24 m)"]'),
('143', 'ROMPECABEZAS 12', '234', 'JugandoAprendo', '["Encaja varias piezas en un tablero, adecuando sus manos y dedos","Comprende indicaciones sencillas realizando la acción (13-18 m) un poco forzada"]'),
('143', 'ADIVINO Y EMPAREJO', '240', 'JugandoAprendo', '["Reconoce un objeto a partir del olor, sabor, textura, sonido, aún sin verlo","Busca objetos conocidos aunque no los tenga a la vista (19-24"]'),
('143', 'LIBRO 11: MARÍA Y JUAN JUEGAN CON COLORES', '266', 'CuentameCuento', '["El niño conversa con mamá y disfruta del cuento."]'),
('144', 'UN ALMUERZO PARA MIS INVITADOS', '93', 'VidaFamilia', '[]'),
('144', 'DIBUJO CON MAMA', '197', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Nombra objetos familiares que observa en ilustraciones"]'),
('144', 'MIS PRIMEROS DIBUJOS', '196', 'JugandoAprendo', '["Garabatea libremente con mayor control de su movimiento","Dice el nombre a sus dibujos, pinturas y modelados y los explica"]'),
('144', 'SECUENCIA 7: VAMOS A PASTOREAR', '255', 'CuentameCuento', '["El niño conversa con mamá y disfruta del cuento."]');